import { a, chapter, n, o, p, v } from "./make";

/** Kappale 2, pages 28–45. Word list p. 45; grammar pp. 31, 36–38. */
export const chapter2 = chapter({
  id: 2,
  label: "Kappale 2",
  title: "Talvikirppis",
  topics: "Hobbies and free time, flea markets, reading adverts",
  structures: "Plural partitive in sentences; the i-plural",
  groups: [
    {
      id: "vocab",
      title: "Word list",
      section: "words",
      general: true,
      pages: [45],
      entries: [
        n("asiakas", "customer", "asiakkaan", "asiakkaita"),
        n("astia", "dish, container", "astian", "astioita"),
        n("etelä", "south", "etelän", "-"),
        o("haitata", "bother, hinder", { note: "haitata (4): minua haittaa = it bothers me" }),
        n("herra", "gentleman, Mr", "herran", "herroja"),
        n("huonekalu", "piece of furniture", "huonekalun", "huonekaluja"),
        a("ilmainen", "free (of charge)", "ilmaisen", "ilmaisia"),
        n("itä", "east", "idän", "-"),
        n("jakoavain", "adjustable spanner", "jakoavaimen", "jakoavaimia"),
        v("jumpata", "work out, do gym", 4, "jumppaan", "jumpannut"),
        v("järjestää", "organise, arrange", 1, "järjestän", "järjestänyt"),
        n("kahvakuula", "kettlebell", "kahvakuulan", "kahvakuulia"),
        n("kattila", "saucepan, pot", "kattilan", "kattiloita"),
        a("kauhea", "terrible", "kauhean", "kauheita"),
        n("kehys", "frame", "kehyksen", "kehyksiä"),
        n("kerta", "time (occasion)", "kerran", "kertoja"),
        o("keskeytyä", "be interrupted, stop", { note: "Verb type 1, used in the third person: keskeytyy, on keskeytynyt." }),
        v("kiehua", "boil", 1, "kiehun", "kiehunut"),
        n("kierrätyskeskus", "recycling centre", "kierrätyskeskuksen", "kierrätyskeskuksia"),
        a("kohtuullinen", "reasonable", "kohtuullisen", "kohtuullisia"),
        n("korkkiruuvi", "corkscrew", "korkkiruuvin", "korkkiruuveja"),
        n("kuhina", "bustle, buzz", "kuhinan", "-"),
        n("kypärä", "helmet", "kypärän", "kypäriä"),
        a("käytetty", "used, second-hand", "käytetyn", "käytettyjä"),
        n("lelu", "toy", "lelun", "leluja"),
        n("lentoemäntä", "flight attendant", "lentoemännän", "lentoemäntiä"),
        o("levitä", "spread", { note: "Verb type 4, used in the third person: leviää, on levinnyt." }),
        p("loppua kesken", "run out (before the end)", { note: "loppua (1): loppuu kesken" }),
        v("luvata", "promise", 4, "lupaan", "luvannut"),
        n("länsi", "west", "lännen", "-"),
        v("mainostaa", "advertise", 1, "mainostan", "mainostanut"),
        a("mauton", "tasteless", "mauttoman", "mauttomia"),
        n("meisseli", "screwdriver", "meisselin", "meisseleitä / meisselejä"),
        n("mitta", "measuring tape; measure", "mitan", "mittoja"),
        n("mono", "ski boot", "monon", "monoja"),
        n("mutteri", "nut (for a bolt)", "mutterin", "muttereita / muttereja"),
        a("muutama", "a few", "muutaman", "muutamia"),
        o("nykyään", "nowadays"),
        n("näyttö", "screen, display", "näytön", "näyttöjä"),
        n("ohikulkija", "passer-by", "ohikulkijan", "ohikulkijoita"),
        p("olla kiinnostunut", "be interested (in)", { note: "olla (3): olen kiinnostunut + mistä" }),
        v("osallistua", "take part", 1, "osallistun", "osallistunut", { note: "osallistua + mihin: osallistun kurssille." }),
        p("ottaa selvää", "find out (about)", { note: "ottaa (1): otan selvää + mistä" }),
        a("paikallinen", "local", "paikallisen", "paikallisia"),
        o("pelottaa", "frighten", { note: "pelottaa (1): minua pelottaa = I'm scared" }),
        n("pohjoinen", "north", "pohjoisen", "-"),
        n("pora", "drill", "poran", "poria"),
        n("potkuhousut", "baby's romper trousers", undefined, "potkuhousuja"),
        n("purkki", "jar, tin", "purkin", "purkkeja"),
        v("päättää", "decide; end", 1, "päätän", "päättänyt"),
        n("päätös", "decision", "päätöksen", "päätöksiä"),
        a("rikkinäinen", "broken", "rikkinäisen", "rikkinäisiä"),
        n("rumpu", "drum", "rummun", "rumpuja"),
        n("saha", "saw", "sahan", "sahoja"),
        a("salainen", "secret", "salaisen", "salaisia"),
        n("satama", "harbour, port", "sataman", "satamia"),
        a("siisti", "neat, tidy", "siistin", "siistejä"),
        n("suksi", "ski", "suksen", "suksia"),
        a("suosittu", "popular", "suositun", "suosittuja"),
        a("synkkä", "gloomy, dark", "synkän", "synkkiä"),
        n("syöttötuoli", "high chair", "syöttötuolin", "syöttötuoleja"),
        n("sämpylä", "bread roll", "sämpylän", "sämpylöitä"),
        n("talvihaalari", "winter overall", "talvihaalarin", "talvihaalareita / talvihaalareja"),
        n("tapahtuma", "event", "tapahtuman", "tapahtumia"),
        n("tarvike", "supply, accessory", "tarvikkeen", "tarvikkeita"),
        n("tuoppi", "pint glass, tankard", "tuopin", "tuoppeja"),
        n("turvakaukalo", "infant car seat", "turvakaukalon", "turvakaukaloita / turvakaukaloja"),
        a("tyytyväinen", "satisfied, content", "tyytyväisen", "tyytyväisiä"),
        n("tähti", "star", "tähden", "tähtiä"),
        n("vaahtera", "maple", "vaahteran", "vaahteroita"),
        v("vaivata", "bother, trouble", 4, "vaivaan", "vaivannut"),
        a("vakava", "serious", "vakavan", "vakavia"),
        v("valokuvata", "photograph", 4, "valokuvaan", "valokuvannut"),
        a("vapaa", "free", "vapaan", "vapaita"),
        a("vapaaehtoinen", "voluntary; volunteer", "vapaaehtoisen", "vapaaehtoisia"),
        o("varmaan", "probably"),
        n("vasara", "hammer", "vasaran", "vasaroita"),
        n("vaunu", "carriage; pram", "vaunun", "vaunuja"),
        n("velka", "debt", "velan", "velkoja"),
        n("vertailu", "comparison", "vertailun", "vertailuja"),
        n("väline", "tool, equipment", "välineen", "välineitä"),
        a("värikäs", "colourful", "värikkään", "värikkäitä"),
        a("ylimääräinen", "extra, surplus", "ylimääräisen", "ylimääräisiä"),
      ],
    },
    {
      id: "spoken",
      title: "Spoken language",
      section: "phrases",
      pages: [45],
      entries: [
        p("ihan ok", "fine, pretty OK", { note: "= ihan hyvä" }),
        p("kirppis", "flea market", { cue: "colloquial", note: "kirppis, kirppiksen = kirpputori" }),
        p("mennä mönkään", "go wrong", { cue: "colloquial", note: "mennä (3) mönkään = mennä huonosti" }),
        p("mennä pieleen", "go wrong", { cue: "colloquial", note: "mennä (3) pieleen = mennä huonosti" }),
      ],
    },
  ],
  grammar: [
    {
      id: "c2-partitive-sentences",
      title: "Plural partitive in sentences",
      hints: [
        "Is the plural at the start of the sentence, or after the verb?",
        "At the start: the T-plural (-t). After ovat, after a verb with an unknown number, and after on in a place sentence: the plural partitive.",
      ],
      pages: [31],
      blocks: [
        {
          type: "text",
          text: "The plural partitive answers mitä?, keitä? and millaisia? It usually stands at the end of the sentence. A plural at the start of the sentence is in the T-form (the nominative plural).",
        },
        {
          type: "table",
          head: ["Sentence", "Pattern", "Example"],
          cols: ["base", "base", "text"],
          rows: [
            ["Describing", "T-plural + ovat + plural partitive", "Kirpputorit ovat suosittuja."],
            ["Object: an unknown number", "verb + plural partitive", "Ostin kirppikseltä leluja."],
            ["Object: a partitive verb", "odottaa, rakastaa … + plural partitive", "Oscar odottaa asiakkaita."],
            ["Object: a negative sentence", "ei + verb + plural partitive", "En löydä monoja."],
            ["Place", "place + verb in the singular + plural partitive", "Pihalla on huonekaluja."],
          ],
        },
        {
          type: "text",
          text: "The order changes the meaning: Pöydällä on kirjoja (there are some books on the table) but Kirjat ovat pöydällä (the books are on the table).",
        },
        {
          type: "examples",
          items: [
            { target: "Kirppiksen hinnat ovat kohtuullisia.", base: "The prices at the flea market are reasonable." },
            { target: "Myyjät olivat tyytyväisiä.", base: "The sellers were satisfied." },
            { target: "Ostin pojalle käytettyjä monoja.", base: "I bought my son second-hand ski boots." },
            { target: "Pihalla myydään astioita ja leluja.", base: "Dishes and toys are sold in the yard." },
            { target: "Lelut ovat laatikossa.", base: "The toys are in the box." },
          ],
        },
      ],
      drills: [
        { id: "c2-partitive-sentences-01", prompt: "Kirpputorit ovat ___.", answer: "suosittuja", options: ["suosittuja", "suosittu", "suositut", "suosittua"], hint: "suosittu", base: "Flea markets are popular." },
        { id: "c2-partitive-sentences-02", prompt: "Nämä astiat ovat ___.", answer: "kauheita", options: ["kauheita", "kauhea", "kauheat", "kauheaa"], hint: "kauhea", base: "These dishes are terrible." },
        { id: "c2-partitive-sentences-03", prompt: "Myyjät olivat ___.", answer: "tyytyväisiä", options: ["tyytyväisiä", "tyytyväinen", "tyytyväiset", "tyytyväistä"], hint: "tyytyväinen", base: "The sellers were satisfied." },
        { id: "c2-partitive-sentences-04", prompt: "Hinnat ovat ___.", answer: "kohtuullisia", options: ["kohtuullisia", "kohtuullinen", "kohtuulliset", "kohtuullista"], hint: "kohtuullinen", base: "The prices are reasonable." },
        { id: "c2-partitive-sentences-05", prompt: "Tuolit ovat ___.", answer: "siistejä", options: ["siistejä", "siisti", "siistit", "siistiä"], hint: "siisti", base: "The chairs are tidy." },
        { id: "c2-partitive-sentences-06", prompt: "Työkalut ovat ___.", answer: "rikkinäisiä", options: ["rikkinäisiä", "rikkinäinen", "rikkinäiset", "rikkinäistä"], hint: "rikkinäinen", base: "The tools are broken." },
        { id: "c2-partitive-sentences-07", prompt: "Ostin kirppikseltä ___.", answer: "leluja", options: ["leluja", "lelut", "lelua"], hint: "lelu", base: "I bought (some) toys at the flea market." },
        { id: "c2-partitive-sentences-08", prompt: "Tarvitsen ___ astioita.", answer: "uusia", options: ["uusia", "uudet", "uutta"], hint: "uusi", base: "I need new dishes." },
        { id: "c2-partitive-sentences-09", prompt: "Oscar odottaa ___.", answer: "asiakkaita", options: ["asiakkaita", "asiakkaat", "asiakasta"], hint: "asiakas", base: "Oscar is waiting for customers." },
        { id: "c2-partitive-sentences-10", prompt: "En löydä ___.", answer: "monoja", options: ["monoja", "monot", "monoa"], hint: "mono", base: "I can't find my ski boots." },
        { id: "c2-partitive-sentences-11", prompt: "Hän ei myy ___.", answer: "huonekaluja", options: ["huonekaluja", "huonekalut", "huonekalua"], hint: "huonekalu", base: "She doesn't sell furniture." },
        { id: "c2-partitive-sentences-12", prompt: "Pihalla on ___.", answer: "huonekaluja", options: ["huonekaluja", "huonekalut", "huonekalua"], hint: "huonekalu", base: "There is furniture in the yard." },
        { id: "c2-partitive-sentences-13", prompt: "___ ovat pihalla.", answer: "Huonekalut", options: ["Huonekalut", "Huonekaluja", "Huonekalua"], hint: "huonekalu", base: "The furniture is in the yard." },
        { id: "c2-partitive-sentences-14", prompt: "Pihalla kävelee ___.", answer: "ihmisiä", options: ["ihmisiä", "ihmiset", "ihmistä"], hint: "ihminen", base: "People are walking in the yard." },
        { id: "c2-partitive-sentences-15", prompt: "Kirppiksellä myydään ___.", answer: "astioita", options: ["astioita", "astiat", "astiaa"], hint: "astia", base: "Dishes are sold at the flea market." },
        { id: "c2-partitive-sentences-16", prompt: "___ ovat laatikossa.", answer: "Lelut", options: ["Lelut", "Leluja", "Lelua"], hint: "lelu", base: "The toys are in the box." },
      ],
    },
    {
      id: "c2-i-plural",
      title: "The i-plural",
      hints: [
        "Look at the last vowel of the word and how long the word is.",
        "o, ö, u and y stay; most a, ä and e drop away; a after a, e or i becomes o; a new word in -i gets -ei-.",
        "Long -la, -na, -ra and -ija words take -oi-; long -ma, -va and -ja words and long adjectives just drop the a.",
      ],
      pages: [36, 37, 38],
      blocks: [
        {
          type: "text",
          text: "In the other cases the plural sign is i. Whenever you add -ssa, -sta, -lle, -lla, -lta, -ksi or -na and mean more than one, the i goes between the stem and the ending. Before it, the stem's last vowel changes in the same way as in the plural partitive.",
        },
        {
          type: "table",
          head: ["Word ends in", "Change", "Example"],
          cols: ["base", "base", "text"],
          rows: [
            ["o, ö, u, y", "+ i", "lelu → leluissa"],
            ["a, ä, e (short words), i → e, -nen, -in, -us", "drop the vowel + i", "synkkä → synkissä"],
            ["-i in a new word", "i → e + i", "purkki → purkeissa"],
            ["a, with a, e or i before it", "a → o + i", "saha → sahoilla"],
            ["a long vowel, a diphthong, -e, -as", "shorten + i", "vapaa → vapailla"],
            ["long -la, -na, -ra, -ija", "a → o + i", "kattila → kattiloissa"],
            ["long -ma, -va, -ja; long adjectives", "drop a + i", "satama → satamissa"],
          ],
        },
        {
          type: "text",
          text: "The pronouns: nämä → näissä, näillä; nuo → noissa, noilla; ne → niissä, niillä.",
        },
        {
          type: "examples",
          items: [
            { target: "Käyn usein kirpputoreilla.", base: "I often go to flea markets." },
            { target: "Lapset leikkivät leluilla.", base: "The children are playing with toys." },
            { target: "Kahvi on purkeissa.", base: "The coffee is in jars." },
            { target: "Laivat ovat satamissa.", base: "The ships are in the harbours." },
            { target: "Pidän värikkäistä vaatteista.", base: "I like colourful clothes." },
          ],
        },
      ],
      drills: [
        { id: "c2-i-plural-01", prompt: "Lapset leikkivät ___.", answer: "leluilla", options: ["leluilla", "lelulla", "leluja"], hint: "lelu", base: "The children are playing with toys." },
        { id: "c2-i-plural-02", prompt: "Talvella liikumme ___.", answer: "suksilla", options: ["suksilla", "suksella", "sukseilla"], hint: "suksi", base: "In winter we get about on skis." },
        { id: "c2-i-plural-03", prompt: "Ruoka on ___.", answer: "kattiloissa", options: ["kattiloissa", "kattilissa", "kattilassa"], hint: "kattila", base: "The food is in the pots." },
        { id: "c2-i-plural-04", prompt: "Rakentajat työskentelevät ___.", answer: "vasaroilla", options: ["vasaroilla", "vasarilla", "vasaralla"], hint: "vasara", base: "The builders work with hammers." },
        { id: "c2-i-plural-05", prompt: "Laivat ovat ___.", answer: "satamissa", options: ["satamissa", "satamoissa", "satamassa"], hint: "satama", base: "The ships are in the harbours." },
        { id: "c2-i-plural-06", prompt: "Hän puhuu ___ asioista.", answer: "vakavista", options: ["vakavista", "vakavoista", "vakavasta"], hint: "vakava", base: "He talks about serious things." },
        { id: "c2-i-plural-07", prompt: "Kahvi on ___.", answer: "purkeissa", options: ["purkeissa", "purkissa", "purkkeissa"], hint: "purkki", base: "The coffee is in jars." },
        { id: "c2-i-plural-08", prompt: "Lapset istuvat ___.", answer: "syöttötuoleissa", options: ["syöttötuoleissa", "syöttötuolissa", "syöttötuoloissa"], hint: "syöttötuoli", base: "The children are sitting in high chairs." },
        { id: "c2-i-plural-09", prompt: "He asuvat ___ asunnoissa.", answer: "siisteissä", options: ["siisteissä", "siistissä", "siistoissa"], hint: "siisti", base: "They live in tidy flats." },
        { id: "c2-i-plural-10", prompt: "Puut seisovat ___ rinteillä.", answer: "synkillä", options: ["synkillä", "synkällä", "synkkoilla"], hint: "synkkä", base: "The trees stand on gloomy slopes." },
        { id: "c2-i-plural-11", prompt: "Kuvat ovat vanhoissa ___.", answer: "kehyksissä", options: ["kehyksissä", "kehyksessä", "kehyksoissa"], hint: "kehys", base: "The pictures are in old frames." },
        { id: "c2-i-plural-12", prompt: "Etsin tavaroita ___.", answer: "kierrätyskeskuksista", options: ["kierrätyskeskuksista", "kierrätyskeskuksesta", "kierrätyskeskukseista"], hint: "kierrätyskeskus", base: "I look for things in recycling centres." },
        { id: "c2-i-plural-13", prompt: "Kirppiksellä on tavaraa ___ hinnoilla.", answer: "kohtuullisilla", options: ["kohtuullisilla", "kohtuullisella", "kohtuullisoilla"], hint: "kohtuullinen", base: "The flea market has things at reasonable prices." },
        { id: "c2-i-plural-14", prompt: "Pidän ___ vaatteista.", answer: "värikkäistä", options: ["värikkäistä", "värikkäästä", "värikäistä"], hint: "värikäs", base: "I like colourful clothes." },
        { id: "c2-i-plural-15", prompt: "Puhuimme ___ paikoista.", answer: "vapaista", options: ["vapaista", "vapaasta", "vapaaista"], hint: "vapaa", base: "We talked about the free places." },
        { id: "c2-i-plural-16", prompt: "Kerro ___ päätöksistä.", answer: "tärkeistä", options: ["tärkeistä", "tärkeästä", "tärkeoistä"], hint: "tärkeä", base: "Tell me about important decisions." },
        { id: "c2-i-plural-17", prompt: "Sain lahjoja ___.", answer: "naapureilta", options: ["naapureilta", "naapurilta", "naapuroilta"], hint: "naapuri", base: "I got presents from the neighbours." },
        { id: "c2-i-plural-18", prompt: "Sain tietoa ___.", answer: "ohikulkijoilta", options: ["ohikulkijoilta", "ohikulkijilta", "ohikulkijalta"], hint: "ohikulkija", base: "I got information from passers-by." },
        { id: "c2-i-plural-19", prompt: "Kenkäsi ovat ___ laatikoissa.", answer: "noissa", options: ["noissa", "nuoissa", "nuolla"], hint: "nuo", base: "Your shoes are in those boxes." },
        { id: "c2-i-plural-20", prompt: "Mitä ___ kaupoissa myydään?", answer: "näissä", options: ["näissä", "nämissä", "näillä"], hint: "nämä", base: "What is sold in these shops?" },
      ],
    },
  ],
});
