import { a, chapter, n, o, p, v } from "./make";

/** Kappale 3, pages 46–69. Word list p. 69; phrases p. 48; grammar pp. 49–53, 56–58. */
export const chapter3 = chapter({
  id: 3,
  label: "Kappale 3",
  title: "Ensimmäiset askeleet",
  topics: "Working life, childcare, reacting in conversation",
  structures: "Plural genitive and illative; the genitive with täytyy; sense verbs",
  groups: [
    {
      id: "vocab",
      title: "Word list",
      section: "words",
      general: true,
      pages: [69],
      entries: [
        n("ala", "field (of work)", "alan", "aloja"),
        n("ammattitaito", "professional skill", "ammattitaidon", "-"),
        v("ansaita", "earn, make a living", 5, "ansaitsen", "ansainnut", { note: "ansaita + millä: ansaitsen rahaa siivoamalla." }),
        n("askel", "step", "askeleen", "askelia"),
        o("haitata", "mind, bother", { head: "haitata (4), minua haittaa", note: "minua haittaa = I mind, it bothers me" }),
        a("hankala", "awkward, difficult", "hankalan", "hankalia"),
        n("hoitopaikka", "childcare place", "hoitopaikan", "hoitopaikkoja"),
        o("huolestuttaa", "be worried, worry", { head: "huolestuttaa (1), minua huolestuttaa", note: "minua huolestuttaa = I'm worried" }),
        v("ihastua", "be taken with, fall for", 1, "ihastun", "ihastunut", { note: "ihastua + mihin: ihastuin Helsinkiin." }),
        o("innoissaan", "excited"),
        n("isovanhemmat", "grandparents", undefined, "isovanhempia"),
        v("jaksaa", "have the energy, cope", 1, "jaksan", "jaksanut"),
        n("jousto", "flexibility", "jouston", "joustoja"),
        n("jälki", "trace, mark", "jäljen", "jälkiä"),
        o("järjestyä", "work out, get sorted", { head: "järjestyä (1)", note: "Verb type 1, used in the third person: järjestyy, on järjestynyt." }),
        a("kansainvälinen", "international", "kansainvälisen", "kansainvälisiä"),
        v("kasvaa", "grow", 1, "kasvan", "kasvanut"),
        v("keskittyä", "concentrate", 1, "keskityn", "keskittynyt", { note: "keskittyä + mihin: keskityn opintoihin." }),
        v("kieltäytyä", "refuse, decline", 1, "kieltäydyn", "kieltäytynyt", { note: "kieltäytyä + mistä: kieltäydyin työstä." }),
        n("kokoaikatyö", "full-time job", "kokoaikatyön", "kokoaikatöitä"),
        n("kulkukortti", "access card", "kulkukortin", "kulkukortteja"),
        n("kunta", "municipality", "kunnan", "kuntia"),
        v("kuulostaa", "sound", 1, "kuulostan", "kuulostanut", { note: "kuulostaa + miltä: se kuulostaa hyvältä." }),
        v("kyllästyä", "get fed up (with)", 1, "kyllästyn", "kyllästynyt", { note: "kyllästyä + mihin: kyllästyin talveen." }),
        n("käsite", "concept", "käsitteen", "käsitteitä"),
        n("laina", "loan", "lainan", "lainoja"),
        n("lasku", "bill, invoice", "laskun", "laskuja"),
        n("lastenhoito", "childcare", "lastenhoidon", "-"),
        n("lemmikki", "pet", "lemmikin", "lemmikkejä"),
        n("liike", "shop; movement", "liikkeen", "liikkeitä"),
        v("luottaa", "trust", 1, "luotan", "luottanut", { note: "luottaa + mihin: luotan sinuun." }),
        v("luvata", "promise", 4, "lupaan", "luvannut"),
        n("lääketiede", "medicine (the science)", "lääketieteen", "-"),
        a("mahtava", "wonderful, great", "mahtavan", "mahtavia"),
        o("mielellään", "with pleasure, gladly"),
        n("muistiinpano", "note", "muistiinpanon", "muistiinpanoja"),
        a("määräaikainen", "fixed-term, temporary", "määräaikaisen", "määräaikaisia"),
        n("noppa", "dice", "nopan", "noppia"),
        o("ollenkaan", "at all"),
        a("osa-aikainen", "part-time", "osa-aikaisen", "osa-aikaisia"),
        n("palkka", "pay, salary", "palkan", "palkkoja"),
        n("pelinappula", "game piece", "pelinappulan", "pelinappuloita"),
        o("pelottaa", "be afraid, frighten", { head: "pelottaa (1), minua pelottaa", note: "minua pelottaa = I'm afraid" }),
        v("pettyä", "be disappointed", 1, "petyn", "pettynyt", { note: "pettyä + mihin: petyin ruokaan." }),
        p("pitää yhteyttä", "keep in touch, stay in contact", { head: "pitää (1), pidän yhteyttä", note: "pitää yhteyttä + mihin" }),
        n("pulkka", "sledge", "pulkan", "pulkkia"),
        n("puutarha", "garden", "puutarhan", "puutarhoja"),
        n("päivystys", "emergency clinic; on-call duty", "päivystyksen", "päivystyksiä"),
        n("päiväuni", "nap, afternoon nap", "päiväunen", "päiväunia"),
        v("pärjätä", "manage, get by", 4, "pärjään", "pärjännyt"),
        v("päättää", "decide; end", 1, "päätän", "päättänyt"),
        o("samoin", "likewise, same to you"),
        v("selvitä", "cope, get through", 4, "selviän", "selvinnyt"),
        n("sivutyö", "second job, side job", "sivutyön", "sivutöitä"),
        n("säästö", "saving", "säästön", "säästöjä"),
        v("taitaa", "probably (will); know how", 1, "taidan", "taitanut"),
        n("tila", "space, room", "tilan", "tiloja"),
        n("tilaisuus", "event, occasion, opportunity", "tilaisuuden", "tilaisuuksia"),
        v("toimia", "act, work, function", 1, "toimin", "toiminut"),
        v("tottua", "get used (to)", 1, "totun", "tottunut", { note: "tottua + mihin: totuin pimeään." }),
        p("tulla toimeen", "get by, make ends meet; get along", { head: "tulla (3), tulen toimeen" }),
        n("tulo", "income; arrival", "tulon", "tuloja"),
        n("tutkimus", "research, study", "tutkimuksen", "tutkimuksia"),
        v("tutustua", "get to know", 1, "tutustun", "tutustunut", { note: "tutustua + mihin: tutustuin naapureihin." }),
        a("tyytyväinen", "satisfied, content", "tyytyväisen", "tyytyväisiä", { note: "tyytyväinen + mihin: olen tyytyväinen työhöni." }),
        n("työlupa", "work permit", "työluvan", "työlupia"),
        n("työnantaja", "employer", "työnantajan", "työnantajia"),
        n("työvuoro", "shift", "työvuoron", "työvuoroja"),
        n("ulkomaa", "foreign country", "ulkomaan", "ulkomaita", { note: "Often plural: ulkomailla = abroad." }),
        v("vaatia", "demand, require", 1, "vaadin", "vaatinut"),
        a("vaativa", "demanding", "vaativan", "vaativia"),
        v("vaihdella", "vary", 3, "vaihtelen", "vaihdellut"),
        a("vakituinen", "permanent", "vakituisen", "vakituisia"),
        n("varhaiskasvatus", "early childhood education and care", "varhaiskasvatuksen", "-"),
        n("velka", "debt", "velan", "velkoja"),
        o("äsken", "just now, a moment ago"),
      ],
    },
    {
      id: "reacting",
      title: "Reacting in conversation",
      section: "phrases",
      pages: [48],
      entries: [
        p("Ei kai?", "Surely not?", { cue: "you hear something new" }),
        p("Ihan totta?", "Really?", { cue: "you hear something surprising" }),
        p("Niin on.", "That's right.", { cue: "you agree" }),
        p("Eikä tule!", "No it won't!", { cue: "you disagree" }),
        p("Ai jaa.", "Oh, I see.", { cue: "you hear something new" }),
        p("Olet ihan oikeassa.", "You're quite right.", { cue: "you agree" }),
      ],
    },
    {
      id: "spoken",
      title: "Spoken language",
      section: "phrases",
      pages: [69],
      entries: [
        p("biisi", "song", { cue: "colloquial", note: "biisi, -n = musiikkikappale" }),
        p("jännä", "exciting", { cue: "colloquial", note: "jännä, -n = jännittävä" }),
        p("netti", "the internet", { cue: "colloquial", note: "netti, netin = verkko, internet" }),
        p("niinku", "like (a filler)", { cue: "colloquial", note: "= niin kuin" }),
        p("pomo", "boss", { cue: "colloquial", note: "pomo, -n = esimies" }),
        p("pyörittää", "run (a home, a business, a project)", { cue: "colloquial", note: "pyörittää (1), pyöritän = huolehtia esim. kotitöistä, yrityksestä tai projektista" }),
        p("raksa", "building site", { cue: "colloquial", note: "= rakennustyömaa" }),
        p("tienata", "earn", { cue: "colloquial", note: "tienata (4), tienaan = saada rahaa, ansaita" }),
        p("tyyppi", "guy, person", { cue: "colloquial", note: "tyyppi, tyypin = henkilö, ihminen" }),
      ],
    },
  ],
  grammar: [
    {
      id: "c3-plural-genitive",
      title: "Plural genitive",
      hints: [
        "Start from the plural partitive.",
        "-ja/-jä → -jen, -ia/-iä → -ien, -ita/-itä → -iden; long -oita words → -oiden.",
      ],
      pages: [50, 51, 52, 53],
      blocks: [
        {
          type: "text",
          text: "The plural genitive answers keiden? and minkä? about more than one. The easiest way to it is through the plural partitive: the ending of the partitive tells you the ending of the genitive.",
        },
        {
          type: "table",
          head: ["Plural partitive", "Plural genitive", "Example"],
          cols: ["base", "base", "text"],
          rows: [
            ["-ja/-jä", "-jen", "palkkoja → palkkojen"],
            ["-ia/-iä", "-ien", "kuntia → kuntien"],
            ["-ita/-itä", "-iden", "sivutöitä → sivutöiden"],
            ["-oita/-öitä (long words)", "-oiden/-öiden", "pelinappuloita → pelinappuloiden"],
            ["-ia/-iä (long -ma, -va, -ja, adjectives)", "-ien", "työnantajia → työnantajien"],
            ["long -li, -ri, -lo, -lö, -ro, -kko, -kkö", "-jen/-ien or -iden", "muistiinpanojen"],
          ],
        },
        {
          type: "text",
          text: "Words of the pieni, nainen, puhelin, rakennus and työtön types have a second genitive in -ten: naisten, tutkimusten. So do a few old words: lapsi → lasten, mies → miesten. The endings -iden and -itten mean the same. The pronouns: nämä → näiden, nuo → noiden, ne → niiden.",
        },
        {
          type: "examples",
          items: [
            { target: "Hoitajien työvuorot vaihtelevat.", base: "Nurses' shifts vary." },
            { target: "Isovanhempien talossa on paljon tilaa.", base: "There's a lot of room in the grandparents' house." },
            { target: "Kuntien palkat ovat pieniä.", base: "Municipal pay is low." },
            { target: "Pitkien työvuorojen jälkeen olen väsynyt.", base: "After long shifts I'm tired." },
            { target: "Lemmikkien määrä kasvaa.", base: "The number of pets is growing." },
          ],
        },
      ],
      drills: [
        { id: "c3-plural-genitive-01", prompt: "___ työvuorot vaihtelevat.", answer: "Hoitajien", options: ["Hoitajien", "Hoitajoiden", "Hoitajia"], hint: "hoitaja", base: "Nurses' shifts vary." },
        { id: "c3-plural-genitive-02", prompt: "Hän luottaa ___ apuun.", answer: "ystävien", options: ["ystävien", "ystäviä", "ystävät"], hint: "ystävä", base: "She relies on her friends' help." },
        { id: "c3-plural-genitive-03", prompt: "___ talossa on paljon tilaa.", answer: "Isovanhempien", options: ["Isovanhempien", "Isovanhempia", "Isovanhemmat"], hint: "isovanhemmat", base: "There's a lot of room in the grandparents' house." },
        { id: "c3-plural-genitive-04", prompt: "Pitkien ___ jälkeen olen väsynyt.", answer: "työvuorojen", options: ["työvuorojen", "työvuoroiden", "työvuoroja"], hint: "työvuoro", base: "After long shifts I'm tired." },
        { id: "c3-plural-genitive-05", prompt: "___ hoitopaikat ovat kaukana.", answer: "Lasten", options: ["Lasten", "Lapsia", "Lapset"], hint: "lapsi", base: "The children's day-care places are far away.", alt: ["Lapsien"] },
        { id: "c3-plural-genitive-06", prompt: "Monien ___ palkka on pieni.", answer: "työntekijöiden", options: ["työntekijöiden", "työntekijien", "työntekijöitä"], hint: "työntekijä", base: "Many workers' pay is low." },
        { id: "c3-plural-genitive-07", prompt: "___ määrä kasvaa.", answer: "Lemmikkien", options: ["Lemmikkien", "Lemmikkejen", "Lemmikkejä"], hint: "lemmikki", base: "The number of pets is growing." },
        { id: "c3-plural-genitive-08", prompt: "Asun ___ lähellä.", answer: "kauppojen", options: ["kauppojen", "kauppoiden", "kauppoja"], hint: "kauppa", base: "I live near the shops." },
        { id: "c3-plural-genitive-09", prompt: "Kioski on noiden ___ takana.", answer: "puiden", options: ["puiden", "puujen", "puita"], hint: "puu", base: "The kiosk is behind those trees." },
        { id: "c3-plural-genitive-10", prompt: "Luin ___ tulokset.", answer: "tutkimusten", options: ["tutkimusten", "tutkimuksia", "tutkimuksiden"], hint: "tutkimus", base: "I read the results of the studies.", alt: ["tutkimuksien"] },
        { id: "c3-plural-genitive-11", prompt: "___ työntekijöiden palkat ovat pieniä.", answer: "Osa-aikaisten", options: ["Osa-aikaisten", "Osa-aikaisia", "Osa-aikaiset"], hint: "osa-aikainen", base: "Part-time workers' pay is low.", alt: ["Osa-aikaisien"] },
        { id: "c3-plural-genitive-12", prompt: "___ hinnat nousevat.", answer: "Ravintoloiden", options: ["Ravintoloiden", "Ravintolien", "Ravintoloita"], hint: "ravintola", base: "Restaurant prices are rising." },
        { id: "c3-plural-genitive-13", prompt: "Tämä on ___ yhteinen auto.", answer: "naapurien", options: ["naapurien", "naapureita", "naapurit"], hint: "naapuri", base: "This is the neighbours' shared car.", alt: ["naapureiden"] },
        { id: "c3-plural-genitive-14", prompt: "___ työt ovat kiinnostavia.", answer: "Kuntien", options: ["Kuntien", "Kuntojen", "Kuntia"], hint: "kunta", base: "Jobs in the municipalities are interesting." },
        { id: "c3-plural-genitive-15", prompt: "Puhun ___ ihmisten kanssa.", answer: "näiden", options: ["näiden", "nämien", "näitä"], hint: "nämä", base: "I'm talking with these people." },
        { id: "c3-plural-genitive-16", prompt: "Hän maksaa ___ korkoja.", answer: "lainojen", options: ["lainojen", "lainoiden", "lainoja"], hint: "laina", base: "He pays interest on loans." },
        { id: "c3-plural-genitive-17", prompt: "Nuoret tekevät kahta työtä ___ palkkojen takia.", answer: "matalien", options: ["matalien", "matalojen", "matalia"], hint: "matala", base: "Young people do two jobs because of low pay." },
        { id: "c3-plural-genitive-18", prompt: "___ määrä on kasvanut.", answer: "Sivutöiden", options: ["Sivutöiden", "Sivutyöjen", "Sivutöitä"], hint: "sivutyö", base: "The number of side jobs has grown." },
      ],
    },
    {
      id: "c3-genitive-use",
      title: "When to use the genitive",
      hints: [
        "Whose is it, who must do it, or which word comes after it?",
        "Owning, postpositions (takana, edessä, takia …) and necessity (täytyy, pitää, on pakko, ei tarvitse, kannattaa) all take the genitive.",
      ],
      pages: [53],
      blocks: [
        {
          type: "text",
          text: "The genitive shows owning or belonging: whose is it? It also stands before postpositions such as takana, edessä, päällä, alla and lähellä, and before takia and vuoksi (because of).",
        },
        {
          type: "text",
          text: "In a sentence of necessity the person who must, need not or should do something is in the genitive: Meidän täytyy lähteä. The same goes for pitää, on pakko, ei tarvitse and kannattaa.",
        },
        {
          type: "table",
          head: ["Use", "Example"],
          cols: ["base", "text"],
          rows: [
            ["owning, belonging", "Hoitajien työvuorot vaihtelevat."],
            ["before a postposition", "Kioski on talon takana."],
            ["takia, vuoksi (because of)", "Olen väsynyt yövuorojen takia."],
            ["täytyy, pitää, on pakko", "Meidän täytyy lähteä aikaisin."],
            ["ei tarvitse", "Sinun ei tarvitse tulla."],
            ["kannattaa", "Annan kannattaa hakea työtä."],
          ],
        },
        {
          type: "examples",
          items: [
            { target: "Meidän täytyy lähteä kuudelta.", base: "We have to leave at six." },
            { target: "Hänen ei tarvitse tehdä yövuoroja.", base: "She doesn't have to do night shifts." },
            { target: "Sinun kannattaa kysyä pomolta.", base: "You should ask the boss." },
            { target: "Lapset leikkivät pöydän alla.", base: "The children are playing under the table." },
            { target: "Heikillä on kiire kotiin koiran takia.", base: "Heikki is in a hurry to get home because of the dog." },
          ],
        },
      ],
      drills: [
        { id: "c3-genitive-use-01", prompt: "___ täytyy lähteä aamulla aikaisin.", answer: "Meidän", options: ["Meidän", "Me", "Meitä"], hint: "me", base: "We have to leave early in the morning." },
        { id: "c3-genitive-use-02", prompt: "___ ei tarvitse tulla huomenna.", answer: "Sinun", options: ["Sinun", "Sinä", "Sinua"], hint: "sinä", base: "You don't have to come tomorrow." },
        { id: "c3-genitive-use-03", prompt: "___ pitää sopia työvuoroista.", answer: "Esimiehen", options: ["Esimiehen", "Esimies", "Esimiestä"], hint: "esimies", base: "The supervisor must agree on the shifts." },
        { id: "c3-genitive-use-04", prompt: "___ kannattaa hakea uutta työtä.", answer: "Annan", options: ["Annan", "Anna", "Annaa"], hint: "Anna", base: "Anna should apply for a new job." },
        { id: "c3-genitive-use-05", prompt: "___ on pakko säästää rahaa.", answer: "Heidän", options: ["Heidän", "He", "Heitä"], hint: "he", base: "They have to save money." },
        { id: "c3-genitive-use-06", prompt: "___ täytyy keskittyä opintoihin.", answer: "Opiskelijoiden", options: ["Opiskelijoiden", "Opiskelijat", "Opiskelijoita"], hint: "opiskelijat", base: "The students must concentrate on their studies." },
        { id: "c3-genitive-use-07", prompt: "___ ei kannata ottaa lainaa.", answer: "Teidän", options: ["Teidän", "Te", "Teitä"], hint: "te", base: "You (all) shouldn't take out a loan." },
        { id: "c3-genitive-use-08", prompt: "Olen väsynyt ___ takia.", answer: "yövuorojen", options: ["yövuorojen", "yövuoroja", "yövuorot"], hint: "yövuorot", base: "I'm tired because of the night shifts." },
        { id: "c3-genitive-use-09", prompt: "Liikenne pysähtyi ___ vuoksi.", answer: "onnettomuuden", options: ["onnettomuuden", "onnettomuutta", "onnettomuus"], hint: "onnettomuus", base: "The traffic stopped because of the accident." },
        { id: "c3-genitive-use-10", prompt: "Kioski on ___ edessä.", answer: "talon", options: ["talon", "taloa", "talo"], hint: "talo", base: "The kiosk is in front of the house." },
        { id: "c3-genitive-use-11", prompt: "Lapset leikkivät ___ alla.", answer: "pöydän", options: ["pöydän", "pöytää", "pöytä"], hint: "pöytä", base: "The children are playing under the table." },
        { id: "c3-genitive-use-12", prompt: "Kenen auto tämä on? Se on ___.", answer: "minun", options: ["minun", "minä", "minua"], hint: "minä", base: "Whose car is this? It's mine." },
        { id: "c3-genitive-use-13", prompt: "___ lapset ovat päiväkodissa.", answer: "Annan", options: ["Annan", "Anna", "Annaa"], hint: "Anna", base: "Anna's children are at day care." },
        { id: "c3-genitive-use-14", prompt: "Asun ___ lähellä.", answer: "sataman", options: ["sataman", "satamaa", "satama"], hint: "satama", base: "I live near the harbour." },
      ],
    },
    {
      id: "c3-plural-illative",
      title: "Plural illative",
      hints: [
        "Start from the plural partitive.",
        "-ja/-jä → -ihin, -ia/-iä → -iin, -ita/-itä → -isiin; one-syllable words with a long vowel take -ihin (maihin).",
      ],
      pages: [56, 57],
      blocks: [
        {
          type: "text",
          text: "The plural illative answers mihin? and keihin? about more than one: into, onto or towards things. Like the genitive, it is easiest to reach through the plural partitive.",
        },
        {
          type: "table",
          head: ["Word", "Plural partitive", "Plural genitive", "Plural illative"],
          cols: ["target", "target", "target", "target"],
          rows: [
            ["työvuoro", "työvuoroja", "työvuorojen", "työvuoroihin"],
            ["palkka", "palkkoja", "palkkojen", "palkkoihin"],
            ["lemmikki", "lemmikkejä", "lemmikkien", "lemmikkeihin"],
            ["kunta", "kuntia", "kuntien", "kuntiin"],
            ["tutkimus", "tutkimuksia", "tutkimusten", "tutkimuksiin"],
            ["käsite", "käsitteitä", "käsitteiden", "käsitteisiin"],
            ["sivutyö", "sivutöitä", "sivutöiden", "sivutöihin"],
          ],
        },
        {
          type: "text",
          text: "So -ja/-jä becomes -ihin, -ia/-iä becomes -iin and -ita/-itä becomes -isiin. One-syllable words with a long vowel or a diphthong take -ihin: työ → töihin, maa → maihin. Words like nopea and radio: nopeisiin, radioihin.",
        },
        {
          type: "examples",
          items: [
            { target: "Olen tottunut pitkiin työvuoroihin.", base: "I'm used to long shifts." },
            { target: "Hän tutustui uusiin työkavereihin.", base: "She got to know her new colleagues." },
            { target: "Erik lähti moniin Aasian maihin.", base: "Erik went to many Asian countries." },
            { target: "Vastasin kaikkiin kysymyksiin.", base: "I answered all the questions." },
            { target: "Kalle ja Pekka pettyivät pieniin annoksiin.", base: "Kalle and Pekka were disappointed by the small portions." },
          ],
        },
      ],
      drills: [
        { id: "c3-plural-illative-01", prompt: "Olen tottunut ___ aamuihin.", answer: "kylmiin", options: ["kylmiin", "kylmihin", "kylmisiin"], hint: "kylmä", base: "I'm used to cold mornings." },
        { id: "c3-plural-illative-02", prompt: "Jakub tutustui ___.", answer: "naapureihin", options: ["naapureihin", "naapureisiin", "naapureita"], hint: "naapurit", base: "Jakub got to know the neighbours." },
        { id: "c3-plural-illative-03", prompt: "Olen kyllästynyt ___ aamuihin.", answer: "pimeisiin", options: ["pimeisiin", "pimeihin", "pimeiin"], hint: "pimeä", base: "I'm fed up with dark mornings." },
        { id: "c3-plural-illative-04", prompt: "He ovat tottuneet ___ työpäiviin.", answer: "pitkiin", options: ["pitkiin", "pitkihin", "pitkoihin"], hint: "pitkä", base: "They are used to long working days." },
        { id: "c3-plural-illative-05", prompt: "He pettyivät ravintolan ___ annoksiin.", answer: "pieniin", options: ["pieniin", "pienihin", "pienisiin"], hint: "pieni", base: "They were disappointed by the restaurant's small portions." },
        { id: "c3-plural-illative-06", prompt: "Vastasin kaikkiin ___.", answer: "kysymyksiin", options: ["kysymyksiin", "kysymyksihin", "kysymyksisiin"], hint: "kysymykset", base: "I answered all the questions." },
        { id: "c3-plural-illative-07", prompt: "Tänä keväänä keskityn ___.", answer: "opintoihin", options: ["opintoihin", "opintoisiin", "opintoiin"], hint: "opinnot", base: "This spring I'm concentrating on my studies." },
        { id: "c3-plural-illative-08", prompt: "Erik lähti ___ Aasian maihin.", answer: "moniin", options: ["moniin", "monihin", "monisiin"], hint: "moni", base: "Erik went to many Asian countries." },
        { id: "c3-plural-illative-09", prompt: "Erik lähti moniin Aasian ___.", answer: "maihin", options: ["maihin", "maisiin", "maiin"], hint: "maat", base: "Erik went to many Asian countries." },
        { id: "c3-plural-illative-10", prompt: "Miksi ette luota myyjän ___?", answer: "lupauksiin", options: ["lupauksiin", "lupauksihin", "lupauksisiin"], hint: "lupaukset", base: "Why don't you trust the seller's promises?" },
        { id: "c3-plural-illative-11", prompt: "Teidän täytyy ottaa yhteyttä ___.", answer: "viranomaisiin", options: ["viranomaisiin", "viranomaisihin", "viranomaisisiin"], hint: "viranomaiset", base: "You must contact the authorities." },
        { id: "c3-plural-illative-12", prompt: "Laitoin vaatteet ___.", answer: "kaappeihin", options: ["kaappeihin", "kaappeisiin", "kaappiihin"], hint: "kaapit", base: "I put the clothes in the cupboards." },
        { id: "c3-plural-illative-13", prompt: "Erik vertaili junalippuja ___.", answer: "lentoihin", options: ["lentoihin", "lentoisiin", "lentoiin"], hint: "lennot", base: "Erik compared train tickets with flights." },
        { id: "c3-plural-illative-14", prompt: "Marja pukeutuu ___.", answer: "työhousuihin", options: ["työhousuihin", "työhousuisiin", "työhousuiin"], hint: "työhousut", base: "Marja puts on work trousers." },
        { id: "c3-plural-illative-15", prompt: "Tyyne rakastui Juhanin ___ silmiin.", answer: "sinisiin", options: ["sinisiin", "sinisihin", "sinisisiin"], hint: "sininen", base: "Tyyne fell in love with Juhani's blue eyes." },
        { id: "c3-plural-illative-16", prompt: "Hän lähti ___ seikkailuihin.", answer: "uusiin", options: ["uusiin", "uusihin", "uusisiin"], hint: "uusi", base: "He set off on new adventures." },
        { id: "c3-plural-illative-17", prompt: "Kahvi kuuluu Tyynen ___.", answer: "rutiineihin", options: ["rutiineihin", "rutiineisiin", "rutiiniin"], hint: "rutiinit", base: "Coffee is part of Tyyne's routines." },
        { id: "c3-plural-illative-18", prompt: "Totuin nopeasti ___ hintoihin.", answer: "korkeisiin", options: ["korkeisiin", "korkeihin", "korkeiin"], hint: "korkea", base: "I quickly got used to the high prices." },
      ],
    },
    {
      id: "c3-illative-verbs",
      title: "Verbs that take mihin",
      hints: [
        "Which question does the verb ask? These ask mihin? or keihin?",
        "Singular: -Vn, -hVn or -seen; plural: -ihin, -iin or -isiin.",
      ],
      pages: [58],
      blocks: [
        {
          type: "text",
          text: "The illative is not only for moving into a place. Many verbs simply require it: you get used to something, trust somebody, are disappointed in something. Learn each verb together with its question, mihin? or keihin?",
        },
        {
          type: "table",
          head: ["Verb", "Meaning"],
          cols: ["target", "base"],
          rows: [
            ["tutustua", "get to know"],
            ["ihastua", "be taken with"],
            ["rakastua", "fall in love with"],
            ["pukeutua", "dress in"],
            ["vastata", "answer"],
            ["keskittyä", "concentrate on"],
            ["tottua", "get used to"],
            ["kyllästyä", "get fed up with"],
            ["pettyä", "be disappointed in"],
            ["unohtaa", "forget (somewhere)"],
            ["vaihtaa", "change into"],
            ["kuulua", "belong to, be part of"],
            ["luottaa", "trust"],
            ["ottaa yhteyttä", "contact"],
            ["vertailla", "compare with"],
          ],
        },
        {
          type: "examples",
          items: [
            { target: "Olen kyllästynyt talveen.", base: "I'm fed up with winter." },
            { target: "Hän ei luota minuun.", base: "She doesn't trust me." },
            { target: "Keskityn nyt työhön.", base: "Now I'm concentrating on work." },
            { target: "Unohdin puhelimen autoon.", base: "I forgot my phone in the car." },
            { target: "Ota yhteyttä työnantajaan.", base: "Contact the employer." },
          ],
        },
      ],
      drills: [
        { id: "c3-illative-verbs-01", prompt: "Olen kyllästynyt ___.", answer: "talveen", options: ["talveen", "talvesta", "talvella"], hint: "talvi", base: "I'm fed up with winter." },
        { id: "c3-illative-verbs-02", prompt: "Tutustuin uusiin ___.", answer: "työkavereihin", options: ["työkavereihin", "työkavereita", "työkavereille"], hint: "työkaverit", base: "I got to know my new colleagues." },
        { id: "c3-illative-verbs-03", prompt: "Hän ei luota ___.", answer: "minuun", options: ["minuun", "minua", "minulle"], hint: "minä", base: "She doesn't trust me." },
        { id: "c3-illative-verbs-04", prompt: "Keskityn nyt ___.", answer: "työhön", options: ["työhön", "työtä", "työssä"], hint: "työ", base: "Now I'm concentrating on work." },
        { id: "c3-illative-verbs-05", prompt: "Pettyin ravintolan ___.", answer: "ruokaan", options: ["ruokaan", "ruokaa", "ruoalla"], hint: "ruoka", base: "I was disappointed in the restaurant's food." },
        { id: "c3-illative-verbs-06", prompt: "Totuin nopeasti Suomen ___.", answer: "ilmastoon", options: ["ilmastoon", "ilmastoa", "ilmastolla"], hint: "ilmasto", base: "I quickly got used to the Finnish climate." },
        { id: "c3-illative-verbs-07", prompt: "Ota yhteyttä ___.", answer: "työnantajaan", options: ["työnantajaan", "työnantajaa", "työnantajasta"], hint: "työnantaja", base: "Contact the employer." },
        { id: "c3-illative-verbs-08", prompt: "Hän ihastui ___.", answer: "Helsinkiin", options: ["Helsinkiin", "Helsingissä", "Helsinkiä"], hint: "Helsinki", base: "She fell for Helsinki." },
        { id: "c3-illative-verbs-09", prompt: "Vastaa ___!", answer: "kysymykseen", options: ["kysymykseen", "kysymystä", "kysymyksessä"], hint: "kysymys", base: "Answer the question!" },
        { id: "c3-illative-verbs-10", prompt: "Osallistun ___.", answer: "kokoukseen", options: ["kokoukseen", "kokousta", "kokouksessa"], hint: "kokous", base: "I'm taking part in the meeting." },
        { id: "c3-illative-verbs-11", prompt: "Kahvi kuuluu ___.", answer: "aamuun", options: ["aamuun", "aamua", "aamulla"], hint: "aamu", base: "Coffee is part of the morning." },
        { id: "c3-illative-verbs-12", prompt: "Hän rakastui ___.", answer: "naapuriin", options: ["naapuriin", "naapuria", "naapurilla"], hint: "naapuri", base: "She fell in love with the neighbour." },
        { id: "c3-illative-verbs-13", prompt: "Unohdin puhelimen ___.", answer: "autoon", options: ["autoon", "autoa", "autolle"], hint: "auto", base: "I forgot my phone in the car." },
        { id: "c3-illative-verbs-14", prompt: "Marja pukeutui ___.", answer: "mekkoon", options: ["mekkoon", "mekkoa", "mekolla"], hint: "mekko", base: "Marja put on a dress." },
        { id: "c3-illative-verbs-15", prompt: "Mökillä Pekka vaihtoi kengät ___.", answer: "kumisaappaisiin", options: ["kumisaappaisiin", "kumisaappaita", "kumisaappailla"], hint: "kumisaappaat", base: "At the cottage Pekka changed his shoes for rubber boots." },
        { id: "c3-illative-verbs-16", prompt: "Olen tyytyväinen ___.", answer: "palkkaan", options: ["palkkaan", "palkkaa", "palkassa"], hint: "palkka", base: "I'm happy with the pay." },
      ],
    },
    {
      id: "c3-sense-verbs",
      title: "Sense verbs + miltä",
      hints: [
        "How does it seem? Ask miltä?",
        "After a sense verb the describing word takes -lta/-ltä.",
      ],
      pages: [49],
      blocks: [
        {
          type: "text",
          text: "Verbs of the senses say how something comes across: how it sounds, looks, feels, tastes or smells. The word that describes it is in the ablative (-lta/-ltä), the form that answers miltä?",
        },
        {
          type: "table",
          head: ["Verb", "Sense", "Example"],
          cols: ["target", "base", "text"],
          rows: [
            ["kuulostaa", "hearing", "Se kuulostaa hyvältä."],
            ["näyttää", "sight", "Sinä näytät väsyneeltä."],
            ["tuntua", "touch, feeling", "Vesi tuntuu kylmältä."],
            ["maistua", "taste", "Keitto maistuu hyvältä."],
            ["tuoksua", "smell (pleasant)", "Leipä tuoksuu ihanalta."],
            ["haista", "smell (unpleasant)", "Kala haisee pahalta."],
          ],
        },
        {
          type: "examples",
          items: [
            { target: "Suunnitelma kuulostaa hyvältä.", base: "The plan sounds good." },
            { target: "Talviuinti tuntuu mahtavalta.", base: "Winter swimming feels great." },
            { target: "Uusi työ näyttää vaativalta.", base: "The new job looks demanding." },
            { target: "Kahvi maistuu mauttomalta.", base: "The coffee tastes of nothing." },
          ],
        },
      ],
      drills: [
        { id: "c3-sense-verbs-01", prompt: "Suunnitelma kuulostaa ___.", answer: "hyvältä", options: ["hyvältä", "hyvä", "hyvää"], hint: "hyvä", base: "The plan sounds good." },
        { id: "c3-sense-verbs-02", prompt: "Sinä näytät ___.", answer: "väsyneeltä", options: ["väsyneeltä", "väsynyt", "väsynyttä"], hint: "väsynyt", base: "You look tired." },
        { id: "c3-sense-verbs-03", prompt: "Tuore leipä tuoksuu ___.", answer: "ihanalta", options: ["ihanalta", "ihana", "ihanaa"], hint: "ihana", base: "Fresh bread smells wonderful." },
        { id: "c3-sense-verbs-04", prompt: "Pilaantunut kala haisee ___.", answer: "hirveältä", options: ["hirveältä", "hirveä", "hirveää"], hint: "hirveä", base: "Spoiled fish smells terrible." },
        { id: "c3-sense-verbs-05", prompt: "Meksikolainen ruoka maistuu ___.", answer: "tuliselta", options: ["tuliselta", "tulinen", "tulista"], hint: "tulinen", base: "Mexican food tastes hot." },
        { id: "c3-sense-verbs-06", prompt: "Talviuinti tuntuu ___.", answer: "mahtavalta", options: ["mahtavalta", "mahtava", "mahtavaa"], hint: "mahtava", base: "Winter swimming feels great." },
        { id: "c3-sense-verbs-07", prompt: "Hieno ravintola näyttää ___.", answer: "kalliilta", options: ["kalliilta", "kallis", "kallista"], hint: "kallis", base: "The fancy restaurant looks expensive." },
        { id: "c3-sense-verbs-08", prompt: "Hevimusiikki kuulostaa ___.", answer: "mielenkiintoiselta", options: ["mielenkiintoiselta", "mielenkiintoinen", "mielenkiintoista"], hint: "mielenkiintoinen", base: "Heavy metal sounds interesting." },
        { id: "c3-sense-verbs-09", prompt: "Kahvi maistuu ___.", answer: "mauttomalta", options: ["mauttomalta", "mauton", "mautonta"], hint: "mauton", base: "The coffee tastes of nothing." },
        { id: "c3-sense-verbs-10", prompt: "Uusi työ näyttää ___.", answer: "vaativalta", options: ["vaativalta", "vaativa", "vaativaa"], hint: "vaativa", base: "The new job looks demanding." },
      ],
    },
  ],
});
