import { a, chapter, n, o, p, v } from "./make";

/** Kappale 1, pages 8–27. Word list p. 27; grammar pp. 12, 15–18. */
export const chapter1 = chapter({
  id: 1,
  label: "Kappale 1",
  title: "Peltipoliisi",
  topics: "Driving and traffic, lost property, what the authorities do",
  structures: "Plural partitive; noun types (review)",
  groups: [
    {
      id: "vocab",
      title: "Word list",
      section: "words",
      general: true,
      pages: [27],
      entries: [
        a("arvokas", "valuable", "arvokkaan", "arvokkaita"),
        p("Ei voi olla totta!", "That can't be true!"),
        v("estää", "prevent, stop", 1, "estän", "estänyt"),
        n("etupenkki", "front seat", "etupenkin", "etupenkkejä"),
        o("kannattaa", "be worth (doing)", {
          cue: "with the genitive",
          note: "gen. + kannattaa: Sinun kannattaa ajaa hitaasti.",
        }),
        n("hiki", "sweat", "hien", "-"),
        v("hukata", "lose, misplace", 4, "hukkaan", "hukannut"),
        v("huomata", "notice", 4, "huomaan", "huomannut"),
        n("huutokauppa", "auction", "huutokaupan", "huutokauppoja"),
        v("jarruttaa", "brake", 1, "jarrutan", "jarruttanut"),
        v("jättää", "leave (behind)", 1, "jätän", "jättänyt", { note: "jättää + mihin: jätin laukun autoon." }),
        v("kadota", "disappear, go missing", 4, "katoan", "kadonnut"),
        v("kadottaa", "lose (something)", 1, "kadotan", "kadottanut"),
        v("kiroilla", "swear, curse", 3, "kiroilen", "kiroillut"),
        n("kytkin", "clutch (pedal)", "kytkimen", "kytkimiä"),
        v("kääntyä", "turn", 1, "käännyn", "kääntynyt"),
        n("laki", "law", "lain", "lakeja"),
        v("liukua", "slide, skid", 1, "liu'un", "liukunut"),
        v("lyödä", "hit, strike", 2, "lyön", "lyönyt"),
        v("löytää", "find", 1, "löydän", "löytänyt"),
        n("löytötavaratoimisto", "lost property office", "löytötavaratoimiston", "löytötavaratoimistoja"),
        n("nopeusrajoitus", "speed limit", "nopeusrajoituksen", "nopeusrajoituksia"),
        p("nukkua pommiin", "oversleep", { note: "nukkua (1): nukun pommiin" }),
        n("nyrkki", "fist", "nyrkin", "nyrkkejä"),
        n("omistaja", "owner", "omistajan", "omistajia"),
        a("paikallinen", "local", "paikallisen", "paikallisia"),
        p("painaa pohjaan", "floor it (the pedal)", { note: "painaa (1): painan pohjaan" }),
        v("painaa", "press; weigh", 1, "painan", "painanut"),
        v("palvella", "serve", 3, "palvelen", "palvellut"),
        n("palvelu", "service", "palvelun", "palveluja / palveluita"),
        n("peltipoliisi", "speed camera", "peltipoliisin", "peltipoliiseja"),
        v("peruuttaa", "reverse (a car); cancel", 1, "peruutan", "peruuttanut"),
        n("pikkujoulut", "pre-Christmas party", undefined, "pikkujouluja"),
        v("pudota", "fall, drop", 4, "putoan", "pudonnut"),
        n("puhekieli", "spoken language", undefined, "-"),
        n("ratti", "steering wheel", "ratin", "ratteja"),
        n("risteys", "crossroads, junction", "risteyksen", "risteyksiä"),
        n("rutiini", "routine", "rutiinin", "rutiineja"),
        n("sakko", "fine (penalty)", "sakon", "sakkoja"),
        v("selata", "browse, leaf through", 4, "selaan", "selannut"),
        v("säilyttää", "keep, store", 1, "säilytän", "säilyttänyt"),
        o("tapahtua", "happen", { note: "Verb type 1, used in the third person: tapahtuu, on tapahtunut." }),
        n("tapahtuma", "event", "tapahtuman", "tapahtumia"),
        n("teline", "stand, rack", "telineen", "telineitä"),
        o("tuntua", "feel, seem", { note: "tuntua (1) + miltä: Se tuntuu hyvältä." }),
        n("turvavyö", "seat belt", "turvavyön", "turvavöitä"),
        v("unohtaa", "forget", 1, "unohdan", "unohtanut", { note: "unohtaa + mihin: unohdin puhelimen autoon." }),
        o("uudestaan", "again"),
        n("vaihde", "gear", "vaihteen", "vaihteita"),
        v("vaihtaa", "change, switch", 1, "vaihdan", "vaihtanut"),
        n("verkko", "net, network", "verkon", "verkkoja"),
        n("viittomakieli", "sign language", "viittomakielen", "viittomakieliä"),
        n("vilkku", "indicator, turn signal", "vilkun", "vilkkuja"),
        n("viranomainen", "authority (official body)", "viranomaisen", "viranomaisia"),
        v("välittää", "care; pass on", 1, "välitän", "välittänyt"),
        o("välähtää", "flash", { note: "Verb type 1, used in the third person: välähtää, on välähtänyt." }),
        n("ylinopeus", "speeding", "ylinopeuden", "ylinopeuksia"),
        v("täydentää", "complete, fill in", 1, "täydennän", "täydentänyt"),
        a("uusi", "new", "uuden", "uusia"),
        n("vaimo", "wife", "vaimon", "vaimoja"),
        o("vain", "only, just"),
        a("vanha", "old", "vanhan", "vanhoja"),
        n("Venäjä", "Russia", "Venäjän", "-"),
        a("venäläinen", "Russian", "venäläisen", "venäläisiä"),
        n("vuosi", "year", "vuoden", "vuosia"),
        o("vähän", "a little"),
        n("Yhdysvallat", "the United States", "Yhdysvaltojen", "Yhdysvaltoja"),
        v("ymmärtää", "understand", 1, "ymmärrän", "ymmärtänyt"),
        n("äidinkieli", "mother tongue", "äidinkielen", "äidinkieliä"),
      ],
    },
  ],
  grammar: [
    {
      id: "c1-noun-types",
      title: "Noun types: genitive and partitive",
      hints: [
        "Find the word's type from how it ends.",
        "The genitive adds -n to the word's stem; the partitive adds -a/-ä, or -ta/-tä after a consonant or a long vowel.",
      ],
      pages: [12],
      blocks: [
        {
          type: "text",
          text: "A noun's ending tells you its type, and the type tells you what happens to the stem. The genitive (whose? -n) shows the stem that most other forms are built on. The partitive (-a/-ä or -ta/-tä) has a pattern of its own and often keeps the basic form's consonants.",
        },
        {
          type: "table",
          head: ["Type", "Word", "Genitive", "Partitive"],
          cols: ["base", "target", "target", "target"],
          rows: [
            ["ends in a vowel", "vaimo", "vaimon", "vaimoa"],
            ["-i in a new word", "ratti", "ratin", "rattia"],
            ["i → e", "hiki", "hien", "hikeä"],
            ["i → e, -li, -ni, -ri", "äidinkieli", "äidinkielen", "äidinkieltä"],
            ["-nen", "viranomainen", "viranomaisen", "viranomaista"],
            ["-e", "vaihde", "vaihteen", "vaihdetta"],
            ["-in", "kytkin", "kytkimen", "kytkintä"],
            ["-us, -ys", "risteys", "risteyksen", "risteystä"],
            ["-as", "arvokas", "arvokkaan", "arvokasta"],
            ["-si", "vuosi", "vuoden", "vuotta"],
            ["-nut, -nyt", "kiinnostunut", "kiinnostuneen", "kiinnostunutta"],
            ["-ton, -tön", "työtön", "työttömän", "työtöntä"],
          ],
        },
        {
          type: "text",
          text: "Consonants can weaken in the genitive (sakko → sakon, laki → lain) but come back strong in many words of the -e and -as types (vaihde → vaihteen, arvokas → arvokkaan).",
        },
        {
          type: "examples",
          items: [
            { target: "Tämä on vaimon auto.", base: "This is my wife's car." },
            { target: "Peltipoliisi välähti risteyksen kohdalla.", base: "The speed camera flashed at the crossroads." },
            { target: "En löydä kytkintä.", base: "I can't find the clutch." },
            { target: "Hänellä ei ole uutta autoa.", base: "He doesn't have a new car." },
            { target: "Vuoden lopussa on pikkujoulut.", base: "At the end of the year there's the pre-Christmas party." },
          ],
        },
      ],
      drills: [
        { id: "c1-noun-types-01", prompt: "Tämä on ___ auto.", answer: "vaimon", options: ["vaimon", "vaimoa", "vaimo"], hint: "vaimo", base: "This is my wife's car." },
        { id: "c1-noun-types-02", prompt: "En näe ___ missään.", answer: "vaimoa", options: ["vaimoa", "vaimon", "vaimo"], hint: "vaimo", base: "I can't see my wife anywhere." },
        { id: "c1-noun-types-03", prompt: "Pidä kiinni ___ reunasta.", answer: "ratin", options: ["ratin", "rattia", "ratti"], hint: "ratti", base: "Hold on to the edge of the steering wheel." },
        { id: "c1-noun-types-04", prompt: "Hän ei kääntänyt ___.", answer: "rattia", options: ["rattia", "ratin", "ratti"], hint: "ratti", base: "He didn't turn the steering wheel." },
        { id: "c1-noun-types-05", prompt: "Soppa pyyhki ___ otsalta.", answer: "hien", options: ["hien", "hikeä", "hiki"], hint: "hiki", base: "Soppa wiped the sweat off his forehead." },
        { id: "c1-noun-types-06", prompt: "Hänellä ei ollut ___ ollenkaan.", answer: "hikeä", options: ["hikeä", "hien", "hikiä"], hint: "hiki", base: "He wasn't sweating at all." },
        { id: "c1-noun-types-07", prompt: "___ opettaja on mukava.", answer: "Äidinkielen", options: ["Äidinkielen", "Äidinkieltä", "Äidinkieli"], hint: "äidinkieli", base: "The mother-tongue teacher is nice." },
        { id: "c1-noun-types-08", prompt: "Opiskelen ___ kurssilla.", answer: "viittomakielen", options: ["viittomakielen", "viittomakieltä", "viittomakieli"], hint: "viittomakieli", base: "I'm studying on a sign-language course." },
        { id: "c1-noun-types-09", prompt: "Hän opiskelee ___.", answer: "viittomakieltä", options: ["viittomakieltä", "viittomakielen", "viittomakielia"], hint: "viittomakieli", base: "She studies sign language." },
        { id: "c1-noun-types-10", prompt: "Soitin ___ numeroon.", answer: "viranomaisen", options: ["viranomaisen", "viranomaista", "viranomainen"], hint: "viranomainen", base: "I called the authority's number." },
        { id: "c1-noun-types-11", prompt: "Odotan ___.", answer: "viranomaista", options: ["viranomaista", "viranomaisen", "viranomainen"], hint: "viranomainen", base: "I'm waiting for an official." },
        { id: "c1-noun-types-12", prompt: "Auton ___ vaihtaminen on vaikeaa.", answer: "vaihteen", options: ["vaihteen", "vaihdetta", "vaihde"], hint: "vaihde", base: "Changing the car's gear is difficult." },
        { id: "c1-noun-types-13", prompt: "Hän ei löytänyt oikeaa ___.", answer: "vaihdetta", options: ["vaihdetta", "vaihteen", "vaihdeta"], hint: "vaihde", base: "He couldn't find the right gear." },
        { id: "c1-noun-types-14", prompt: "___ vaihtaminen maksaa paljon.", answer: "Kytkimen", options: ["Kytkimen", "Kytkintä", "Kytkin"], hint: "kytkin", base: "Replacing the clutch costs a lot." },
        { id: "c1-noun-types-15", prompt: "Tässä autossa ei ole ___.", answer: "kytkintä", options: ["kytkintä", "kytkimen", "kytkin"], hint: "kytkin", base: "This car has no clutch." },
        { id: "c1-noun-types-16", prompt: "Käänny ___ jälkeen oikealle.", answer: "risteyksen", options: ["risteyksen", "risteystä", "risteys"], hint: "risteys", base: "Turn right after the crossroads." },
        { id: "c1-noun-types-17", prompt: "En näe ___.", answer: "risteystä", options: ["risteystä", "risteyksen", "risteyksiä"], hint: "risteys", base: "I can't see the crossroads." },
        { id: "c1-noun-types-18", prompt: "Löysin ___ sormuksen.", answer: "arvokkaan", options: ["arvokkaan", "arvokasta", "arvokas"], hint: "arvokas", base: "I found a valuable ring." },
        { id: "c1-noun-types-19", prompt: "Hänellä ei ole mitään ___.", answer: "arvokasta", options: ["arvokasta", "arvokkaan", "arvokkaata"], hint: "arvokas", base: "He has nothing valuable." },
        { id: "c1-noun-types-20", prompt: "___ lopussa on paljon juhlia.", answer: "Vuoden", options: ["Vuoden", "Vuotta", "Vuosi"], hint: "vuosi", base: "There are a lot of parties at the end of the year." },
        { id: "c1-noun-types-22", prompt: "Olen asunut täällä kaksi ___.", answer: "vuotta", options: ["vuotta", "vuoden", "vuosia"], hint: "vuosi", base: "I have lived here for two years." },
        { id: "c1-noun-types-23", prompt: "Puhuin ___ miehen kanssa.", answer: "kiinnostuneen", options: ["kiinnostuneen", "kiinnostunutta", "kiinnostunut"], hint: "kiinnostunut", base: "I talked with an interested man." },
        { id: "c1-noun-types-24", prompt: "Etsin ___ opiskelijaa.", answer: "kiinnostunutta", options: ["kiinnostunutta", "kiinnostuneen", "kiinnostunut"], hint: "kiinnostunut", base: "I'm looking for an interested student." },
        { id: "c1-noun-types-25", prompt: "Hän auttaa ___ miestä.", answer: "työtöntä", options: ["työtöntä", "työttömän", "työtön"], hint: "työtön", base: "She is helping an unemployed man." },
        { id: "c1-noun-types-26", prompt: "Hän puhui ___ naisen kanssa.", answer: "työttömän", options: ["työttömän", "työtöntä", "työtön"], hint: "työtön", base: "He talked with an unemployed woman." },
      ],
    },
    {
      id: "c1-plural-partitive-use",
      title: "When to use the plural partitive",
      hints: [
        "Can you count the thing, and do you know how many there are?",
        "paljon + plural partitive; monta and pari + singular partitive; things you can't count: singular partitive.",
      ],
      pages: [15],
      blocks: [
        {
          type: "text",
          text: "Use the plural partitive for an unknown number of things you can count: after paljon (a lot of), and when you simply say that there are some (Kadulla on autoja).",
        },
        {
          type: "text",
          text: "After monta (many) and pari (a couple of) the noun stays in the singular partitive. Things you cannot count, like coffee or water, take the singular partitive even after paljon. When you mean all of certain known things, the plural takes -t: Hän vei kirjat kirjastoon.",
        },
        {
          type: "table",
          head: ["When", "Form", "Example"],
          cols: ["base", "base", "text"],
          rows: [
            ["paljon + something you can count", "plural partitive", "paljon sakkoja"],
            ["some, an unknown number", "plural partitive", "Kadulla on autoja."],
            ["monta, pari", "singular partitive", "monta sakkoa"],
            ["paljon + something you can't count", "singular partitive", "paljon kahvia"],
            ["all of certain known things", "plural with -t", "Hän vei kirjat kirjastoon."],
          ],
        },
        {
          type: "examples",
          items: [
            { target: "Soppa on saanut paljon sakkoja.", base: "Soppa has had a lot of fines." },
            { target: "Hän sai pari sakkoa viime vuonna.", base: "He got a couple of fines last year." },
            { target: "Löytötavaratoimistossa on lompakoita ja avaimia.", base: "There are wallets and keys at the lost property office." },
            { target: "Avaimet ovat eteisen pöydällä.", base: "The keys are on the hall table." },
            { target: "Juon aamulla paljon kahvia.", base: "I drink a lot of coffee in the morning." },
          ],
        },
      ],
      drills: [
        { id: "c1-plural-partitive-use-01", prompt: "Minulla on paljon ___.", answer: "ystäviä", options: ["ystäviä", "ystävää", "ystävät"], hint: "ystävä", base: "I have a lot of friends." },
        { id: "c1-plural-partitive-use-02", prompt: "Minulla on monta ___.", answer: "ystävää", options: ["ystävää", "ystäviä", "ystävät"], hint: "ystävä", base: "I have many friends." },
        { id: "c1-plural-partitive-use-03", prompt: "Juon aamulla paljon ___.", answer: "kahvia", options: ["kahvia", "kahveja", "kahvit"], hint: "kahvi", base: "I drink a lot of coffee in the morning." },
        { id: "c1-plural-partitive-use-04", prompt: "Juon kesällä paljon ___.", answer: "vettä", options: ["vettä", "vesiä", "vedet"], hint: "vesi", base: "I drink a lot of water in summer." },
        { id: "c1-plural-partitive-use-05", prompt: "Kadulla on paljon ___.", answer: "ihmisiä", options: ["ihmisiä", "ihmistä", "ihmiset"], hint: "ihminen", base: "There are a lot of people in the street." },
        { id: "c1-plural-partitive-use-06", prompt: "Soppa sai pari ___.", answer: "sakkoa", options: ["sakkoa", "sakkoja", "sakot"], hint: "sakko", base: "Soppa got a couple of fines." },
        { id: "c1-plural-partitive-use-07", prompt: "Soppa on saanut paljon ___.", answer: "sakkoja", options: ["sakkoja", "sakkoa", "sakot"], hint: "sakko", base: "Soppa has had a lot of fines." },
        { id: "c1-plural-partitive-use-08", prompt: "Peltipoliisi otti monta ___.", answer: "kuvaa", options: ["kuvaa", "kuvia", "kuvat"], hint: "kuva", base: "The speed camera took many pictures." },
        { id: "c1-plural-partitive-use-09", prompt: "Pöydällä on ___.", answer: "avaimia", options: ["avaimia", "avaimet", "avainta"], hint: "avain", base: "There are (some) keys on the table." },
        { id: "c1-plural-partitive-use-10", prompt: "___ ovat pöydällä.", answer: "Avaimet", options: ["Avaimet", "Avaimia", "Avainta"], hint: "avain", base: "The keys are on the table." },
        { id: "c1-plural-partitive-use-11", prompt: "Hän vei ___ kirjastoon.", answer: "kirjoja", options: ["kirjoja", "kirjat", "kirjaa"], hint: "kirja", base: "She took some books to the library." },
        { id: "c1-plural-partitive-use-12", prompt: "Hän vei ___ kirjastoon.", answer: "kirjat", options: ["kirjat", "kirjoja", "kirjaa"], hint: "kirja", base: "She took the books (all of them) to the library." },
        { id: "c1-plural-partitive-use-13", prompt: "Pihalla on ___.", answer: "autoja", options: ["autoja", "autot", "autoa"], hint: "auto", base: "There are cars in the yard." },
        { id: "c1-plural-partitive-use-14", prompt: "Pihalla on pari ___.", answer: "autoa", options: ["autoa", "autoja", "autot"], hint: "auto", base: "There are a couple of cars in the yard." },
      ],
    },
    {
      id: "c1-plural-partitive",
      title: "Plural partitive: the endings",
      hints: [
        "Look at how the word ends, and how long it is.",
        "The plural sign is i (j between vowels); then comes -a/-ä, or -ta/-tä after a long vowel or an e-stem.",
        "Short words with a, e or i before a final -a change it to o (vanha → vanhoja); long -la, -na, -ra, -ija and -kka words take -oita.",
      ],
      pages: [16, 17, 18],
      blocks: [
        {
          type: "text",
          text: "The plural partitive is built from the stem, the plural sign i (written j between two vowels) and the partitive ending -a/-ä. After a long vowel, a diphthong or an e-stem the ending is -ta/-tä, so the form ends in -ita/-itä.",
        },
        {
          type: "table",
          head: ["Word ends in", "Change", "Example"],
          cols: ["base", "base", "text"],
          rows: [
            ["o, ö, u, y", "+ ja/jä", "vilkku → vilkkuja"],
            ["-i in a new word", "i → e + ja", "ratti → ratteja"],
            ["-a, with a, e or i before it", "a → o + ja", "vanha → vanhoja"],
            ["-a, -ä, -e (other short words)", "drop it + ia/iä", "kesä → kesiä"],
            ["-i → e, -nen, -in, -us, -tön", "stem + ia/iä", "risteys → risteyksiä"],
            ["one syllable, long vowel", "shorten + ita/itä", "turvavyö → turvavöitä"],
            ["-e, -as, -nut", "stem + ita/itä", "teline → telineitä"],
            ["long -la, -na, -ra, -ija, -kka", "a → o + ita", "ravintola → ravintoloita"],
            ["long -ma, -va, -ja; long adjectives", "drop a + ia", "omistaja → omistajia"],
            ["long -li, -lo, -ri, -ro, -kko", "ja or ita", "lompakko → lompakkoja, lompakoita"],
          ],
        },
        {
          type: "text",
          text: "The pronouns have their own forms: me → meitä, te → teitä, he → heitä, nämä → näitä, nuo → noita, ne → niitä.",
        },
        {
          type: "examples",
          items: [
            { target: "Kaupungissa on monia risteyksiä.", base: "There are many junctions in the city." },
            { target: "Autossa on turvavöitä.", base: "There are seat belts in the car." },
            { target: "Hänellä on vanhoja autoja.", base: "He has old cars." },
            { target: "Pihalla on pyörätelineitä.", base: "There are bike racks in the yard." },
            { target: "Peltipoliisi ei etsi meitä.", base: "The speed camera isn't looking for us." },
          ],
        },
      ],
      drills: [
        { id: "c1-plural-partitive-01", prompt: "Kalastajalla on paljon ___.", answer: "verkkoja", options: ["verkkoja", "verkkoita", "verkkoa", "verkot"], hint: "verkko", base: "The fisherman has a lot of nets." },
        { id: "c1-plural-partitive-02", prompt: "Kaupassa on paljon ___.", answer: "vilkkuja", options: ["vilkkuja", "vilkkuita", "vilkkua", "vilkut"], hint: "vilkku", base: "The shop has a lot of indicator lights." },
        { id: "c1-plural-partitive-03", prompt: "Soppa sai paljon ___.", answer: "sakkoja", options: ["sakkoja", "sakkoita", "sakkoa", "sakot"], hint: "sakko", base: "Soppa got a lot of fines." },
        { id: "c1-plural-partitive-04", prompt: "Tiellä oli monia ___.", answer: "peltipoliiseja", options: ["peltipoliiseja", "peltipoliisia", "peltipoliisit"], hint: "peltipoliisi", base: "There were many speed cameras on the road." },
        { id: "c1-plural-partitive-05", prompt: "Autokaupassa on uusia ___.", answer: "ratteja", options: ["ratteja", "rattia", "ratit"], hint: "ratti", base: "The car shop has new steering wheels." },
        { id: "c1-plural-partitive-06", prompt: "Hänellä on ___ autoja.", answer: "vanhoja", options: ["vanhoja", "vanhia", "vanhaa", "vanhat"], hint: "vanha", base: "He has old cars." },
        { id: "c1-plural-partitive-07", prompt: "Kirjastossa on paljon ___.", answer: "kirjoja", options: ["kirjoja", "kirjia", "kirjaa", "kirjat"], hint: "kirja", base: "There are a lot of books in the library." },
        { id: "c1-plural-partitive-08", prompt: "Hän on asunut Suomessa ___.", answer: "vuosia", options: ["vuosia", "vuotta", "vuodet"], hint: "vuosi", base: "She has lived in Finland for years." },
        { id: "c1-plural-partitive-09", prompt: "Hän osti ___ vaatteita.", answer: "uusia", options: ["uusia", "uutta", "uudet"], hint: "uusi", base: "He bought new clothes." },
        { id: "c1-plural-partitive-10", prompt: "Kaupungissa on monia ___.", answer: "risteyksiä", options: ["risteyksiä", "risteyksejä", "risteystä", "risteykset"], hint: "risteys", base: "There are many junctions in the city." },
        { id: "c1-plural-partitive-11", prompt: "Pöydällä on ___.", answer: "avaimia", options: ["avaimia", "avaimeja", "avainta", "avaimet"], hint: "avain", base: "There are keys on the table." },
        { id: "c1-plural-partitive-12", prompt: "Suomessa on monia ___.", answer: "viranomaisia", options: ["viranomaisia", "viranomaista", "viranomaiset"], hint: "viranomainen", base: "There are many authorities in Finland." },
        { id: "c1-plural-partitive-13", prompt: "Autossa on ___.", answer: "turvavöitä", options: ["turvavöitä", "turvavyöjä", "turvavyötä", "turvavyöt"], hint: "turvavyö", base: "There are seat belts in the car." },
        { id: "c1-plural-partitive-14", prompt: "Hänellä on paljon ___.", answer: "töitä", options: ["töitä", "työjä", "työtä", "työt"], hint: "työ", base: "She has a lot of jobs to do." },
        { id: "c1-plural-partitive-15", prompt: "Pihalla on ___.", answer: "telineitä", options: ["telineitä", "telinejä", "telinettä", "telineet"], hint: "teline", base: "There are racks in the yard." },
        { id: "c1-plural-partitive-16", prompt: "Hän osti ___ tauluja.", answer: "arvokkaita", options: ["arvokkaita", "arvokasta", "arvokkaat"], hint: "arvokas", base: "She bought valuable paintings." },
        { id: "c1-plural-partitive-17", prompt: "Kaupungissa on monia ___.", answer: "ravintoloita", options: ["ravintoloita", "ravintolia", "ravintolaa", "ravintolat"], hint: "ravintola", base: "There are many restaurants in the town." },
        { id: "c1-plural-partitive-18", prompt: "Löytötavaratoimistossa on paljon ___.", answer: "lompakoita", options: ["lompakoita", "lompakkoa", "lompakot"], hint: "lompakko", base: "There are a lot of wallets at the lost property office.", alt: ["lompakkoja"] },
        { id: "c1-plural-partitive-19", prompt: "Kaupungissa on ___.", answer: "tapahtumia", options: ["tapahtumia", "tapahtumoita", "tapahtumaa", "tapahtumat"], hint: "tapahtuma", base: "There are events in the town." },
        { id: "c1-plural-partitive-20", prompt: "Yrityksellä on monia ___.", answer: "omistajia", options: ["omistajia", "omistajoita", "omistajaa", "omistajat"], hint: "omistaja", base: "The company has many owners." },
        { id: "c1-plural-partitive-21", prompt: "Torilla myydään ___ tuotteita.", answer: "paikallisia", options: ["paikallisia", "paikallista", "paikalliset"], hint: "paikallinen", base: "Local products are sold at the market." },
        { id: "c1-plural-partitive-22", prompt: "Poliisi etsii ___.", answer: "meitä", options: ["meitä", "meidät", "me"], hint: "me", base: "The police are looking for us." },
        { id: "c1-plural-partitive-23", prompt: "Odotatko ___?", answer: "heitä", options: ["heitä", "heidät", "he"], hint: "he", base: "Are you waiting for them?" },
        { id: "c1-plural-partitive-24", prompt: "En tarvitse ___ kirjoja.", answer: "näitä", options: ["näitä", "nämä", "tätä"], hint: "nämä", base: "I don't need these books." },
      ],
    },
  ],
});
