import { a, chapter, n, o, p, v } from "./make";

/** Kappale 4, pages 70–99. Word list p. 99; phrases pp. 84–85; grammar pp. 74–75, 79, 92. */
export const chapter4 = chapter({
  id: 4,
  label: "Kappale 4",
  title: "Etsitään harjoittelijoita",
  topics: "Work placements, job adverts, phone calls, the CV",
  structures: "Perfect and pluperfect; possessive suffixes",
  groups: [
    {
      id: "vocab",
      title: "Word list",
      section: "words",
      general: true,
      pages: [99],
      entries: [
        a("aiempi", "earlier, previous", "aiemman", "aiempia"),
        n("aikajana", "timeline", "aikajanan", "aikajanoja"),
        v("aikoa", "intend, plan", 1, "aion", "aikonut"),
        n("ala", "field (of work)", "alan", "aloja"),
        o("alasti", "naked"),
        n("alkeet", "the basics", undefined, "alkeita"),
        n("ansioluettelo", "CV, résumé", "ansioluettelon", "ansioluetteloita / ansioluetteloja"),
        n("apulainen", "assistant", "apulaisen", "apulaisia"),
        n("asennus", "installation", "asennuksen", "asennuksia"),
        p("asia koskee", "the matter concerns", { note: "asia koskee + P: Mitä asia koskee?" }),
        n("asiakaspalvelu", "customer service", "asiakaspalvelun", "-"),
        a("erinomainen", "excellent", "erinomaisen", "erinomaisia"),
        n("esimies", "supervisor, manager", "esimiehen", "esimiehiä"),
        v("haista", "smell (bad)", 3, "haisen", "haissut", { note: "haista + miltä: kala haisee pahalta." }),
        v("hakea", "apply (for); fetch", 1, "haen", "hakenut", { note: "hakea + mihin/mille: haen harjoittelupaikkaan." }),
        n("hakemus", "application", "hakemuksen", "hakemuksia"),
        n("henkilöstöpäällikkö", "HR manager", "henkilöstöpäällikön", "henkilöstöpäälliköitä / henkilöstöpäällikköjä"),
        n("henkilötieto", "personal detail", "henkilötiedon", "henkilötietoja"),
        n("huijari", "cheat, swindler", "huijarin", "huijareita / huijareja"),
        v("irvistää", "grimace", 1, "irvistän", "irvistänyt"),
        n("IT-tuki", "IT support", "IT-tuen", "-"),
        o("jatkua", "continue", { note: "Verb type 1, used in the third person: jatkuu, on jatkunut." }),
        p("joka tapauksessa", "in any case"),
        n("joulupukki", "Father Christmas", "joulupukin", "joulupukkeja"),
        n("juhannus", "Midsummer", "juhannuksen", "juhannuksia"),
        p("jäädä odottamaan", "stay and wait", { note: "jäädä (2): jään odottamaan" }),
        v("keskittyä", "concentrate", 1, "keskityn", "keskittynyt", { note: "keskittyä + mihin: keskityn opintoihin." }),
        n("kilpailu", "competition", "kilpailun", "kilpailuja"),
        p("kirjoittaa ylioppilaaksi", "pass the matriculation exam", { note: "kirjoittaa (1): kirjoitan ylioppilaaksi" }),
        a("kokoaikainen", "full-time", "kokoaikaisen", "kokoaikaisia"),
        n("koulutus", "education, training", "koulutuksen", "koulutuksia"),
        a("kunnollinen", "proper, decent", "kunnollisen", "kunnollisia"),
        o("kuulemma", "reportedly, I hear"),
        n("kuvaus", "description", "kuvauksen", "kuvauksia"),
        n("laite", "device, appliance", "laitteen", "laitteita"),
        v("liittää", "attach", 1, "liitän", "liittänyt"),
        n("linja", "line; study programme", "linjan", "linjoja"),
        n("lisätieto", "further information", "lisätiedon", "lisätietoja"),
        n("lukio", "upper secondary school", "lukion", "lukioita"),
        n("mahdollisuus", "possibility, chance", "mahdollisuuden", "mahdollisuuksia"),
        v("maistaa", "taste", 1, "maistan", "maistanut"),
        o("mennessä", "by (a time)", { cue: "with mihin", note: "mihin + mennessä: perjantaihin mennessä" }),
        n("munkki", "doughnut; monk", "munkin", "munkkeja"),
        v("murtua", "break, fracture", 1, "murrun", "murtunut"),
        p("muun muassa", "among other things"),
        n("myymälä", "shop, store", "myymälän", "myymälöitä"),
        n("myyntiala", "sales (field)", "myyntialan", "-"),
        n("ohjelmisto", "software", "ohjelmiston", "ohjelmistoja"),
        p("olla paikalla", "be in, be present", { note: "olla (3): olen paikalla" }),
        p("olla tavattavissa", "be available (to talk)", { note: "olla (3): olen tavattavissa" }),
        o("onnistaa", "be lucky", { note: "onnistaa (1): minua onnistaa = I'm lucky" }),
        n("opinto", "study (course)", "opinnon", "opintoja", { note: "Mostly plural: opinnot." }),
        a("osa-aikainen", "part-time", "osa-aikaisen", "osa-aikaisia"),
        p("ottaa huomioon", "take into account", { note: "ottaa (1): otan huomioon" }),
        p("palata asiaan", "get back to the matter", { note: "palata (4): palaan asiaan" }),
        n("pesäpallo", "Finnish baseball", "pesäpallon", "-"),
        n("piparkakku", "gingerbread biscuit", "piparkakun", "piparkakkuja"),
        v("printata", "print", 4, "printtaan", "printannut"),
        v("pysyä", "stay, remain", 1, "pysyn", "pysynyt"),
        v("päivittää", "update", 1, "päivitän", "päivittänyt"),
        n("rakennusala", "construction industry", "rakennusalan", "-"),
        v("ratkaista", "solve", 3, "ratkaisen", "ratkaissut"),
        n("revontuli", "northern lights", "revontulen", "revontulia", { note: "Mostly plural: revontulet." }),
        v("sairastua", "fall ill", 1, "sairastun", "sairastunut", { note: "sairastua + mihin: sairastuin flunssaan." }),
        n("salibandy", "floorball", "salibandyn", "-"),
        n("salmiakki", "salty liquorice", "salmiakin", "salmiakkeja"),
        o("sattumalta", "by chance"),
        v("selvittää", "find out, sort out", 1, "selvitän", "selvittänyt"),
        v("seurustella", "be dating, go out (with)", 3, "seurustelen", "seurustellut"),
        n("soittopyyntö", "call-back request", "soittopyynnön", "soittopyyntöjä"),
        v("suorittaa", "complete (a degree, a course)", 1, "suoritan", "suorittanut"),
        n("suunnitelma", "plan", "suunnitelman", "suunnitelmia"),
        n("suuntautumisvaihtoehto", "specialisation (option)", "suuntautumisvaihtoehdon", "suuntautumisvaihtoehtoja"),
        v("säästää", "save (money)", 1, "säästän", "säästänyt"),
        a("söpö", "cute", "söpön", "söpöjä"),
        v("tallentaa", "save (a file); record", 1, "tallennan", "tallentanut"),
        v("tarjota", "offer", 4, "tarjoan", "tarjonnut"),
        a("tarkka", "exact, careful", "tarkan", "tarkkoja"),
        v("tarkoittaa", "mean", 1, "tarkoitan", "tarkoittanut"),
        v("tavoitella", "try to reach; aim for", 3, "tavoittelen", "tavoitellut"),
        v("toimia", "act, work, function", 1, "toimin", "toiminut"),
        n("tuki", "support", "tuen", "tukia"),
        n("työharjoittelupaikka", "work placement", "työharjoittelupaikan", "työharjoittelupaikkoja"),
        n("työkokemus", "work experience", "työkokemuksen", "työkokemuksia"),
        o("uudestaan", "again"),
        o("vahingossa", "by accident"),
        a("vakituinen", "permanent", "vakituisen", "vakituisia"),
        a("vapaamuotoinen", "informal, free-form", "vapaamuotoisen", "vapaamuotoisia"),
        n("vappu", "May Day", "vapun", "vappuja"),
        n("varastotyöntekijä", "warehouse worker", "varastotyöntekijän", "varastotyöntekijöitä"),
        a("varattu", "busy, reserved", "varatun", "varattuja"),
        n("verovirasto", "tax office", "veroviraston", "verovirastoja"),
        n("virkailija", "official, clerk", "virkailijan", "virkailijoita"),
        n("yhteystieto", "contact detail", "yhteystiedon", "yhteystietoja"),
        v("yrittää", "try", 1, "yritän", "yrittänyt"),
      ],
    },
    {
      id: "phone",
      title: "Phone phrases",
      section: "phrases",
      pages: [84],
      entries: [
        p("Tässä on Mikko Virtanen, hei!", "Hello, this is Mikko Virtanen!"),
        p("Onkohan Stina Kuusela tavattavissa?", "Is Stina Kuusela available?", { cue: "free to talk" }),
        p("Onkohan Stina Kuusela paikalla?", "Is Stina Kuusela in?", { cue: "at the office" }),
        p("Numero on varattu.", "The line is busy."),
        p("Haluaisin puhua henkilöstöpäällikön kanssa.", "I'd like to speak to the HR manager."),
        p("Voinko jättää soittopyynnön?", "Can I leave a call-back request?"),
        p("Osaatko sanoa, milloin hänelle voi soittaa?", "Can you tell me when I could call them?"),
        p("Palaan asiaan myöhemmin.", "I'll get back to it later."),
      ],
    },
    {
      id: "background",
      title: "Talking about your background",
      section: "phrases",
      pages: [85],
      entries: [
        p("Olen opiskellut 3 vuotta ammattikoulussa.", "I've studied for 3 years at a vocational school."),
        p("Olen opiskellut sairaanhoitajaksi.", "I've trained as a nurse."),
        p("Valmistuin bussinkuljettajaksi vuonna 2022.", "I qualified as a bus driver in 2022."),
        p("Olen ollut työssä 12 vuotta.", "I've been working for 12 years."),
        p("Minulla on viiden vuoden työkokemus rakennusalalta.", "I have five years' work experience in construction."),
        p("Olen tehnyt kuusi vuotta erilaisia myyntialan töitä.", "I've done various sales jobs for six years."),
        p("Kotimaassani opiskelin yliopistossa, nyt olen ollut kotona lasten kanssa.", "In my home country I studied at university; now I've been at home with the children."),
        p("Olen kiinnostunut autonasentajan työstä.", "I'm interested in work as a car mechanic."),
        p("Olen kiinnostunut ravintola-alasta.", "I'm interested in the restaurant industry."),
        p("Aion hakea ammattikouluun lähihoitajalinjalle.", "I'm going to apply to vocational school for the practical-nurse programme."),
        p("Aloitan syksyllä tradenomiopinnot ammattikorkeakoulussa.", "In the autumn I'm starting business studies at a university of applied sciences."),
        p("Olen suorittanut kotimaassani sairaanhoitajan tutkinnon.", "I completed a nursing degree in my home country."),
      ],
    },
    {
      id: "spoken",
      title: "Spoken language",
      section: "phrases",
      pages: [99],
      entries: [
        p("Arvaa mitä?", "Guess what?"),
        p("eskari", "pre-school", { cue: "colloquial", note: "eskari, -n = esikoulu" }),
        p("huono tuuri", "bad luck", { note: "= huono onni" }),
        p("läppäri", "laptop", { cue: "colloquial", note: "läppäri, -n = kannettava tietokone" }),
        p("Mä en kestä!", "I can't stand it!"),
        p("naama", "face", { cue: "colloquial", note: "= kasvot" }),
        p("ollaan käyty", "we've been (to)", { cue: "colloquial", note: "= olemme käyneet" }),
        p("ollaan oltu", "we've been", { cue: "colloquial", note: "= olemme olleet" }),
        p("pitää peukkuja", "keep your fingers crossed", { note: "pitää (1), pidän peukkuja = toivoa onnea jollekin" }),
        p("putiikki", "boutique, small shop", { note: "putiikki, putiikin = (pieni) kauppa" }),
        p("renttu", "slob, rascal", { cue: "colloquial", note: "= huonotapainen ihminen" }),
        p("tarkkaan", "carefully, exactly", { cue: "colloquial", note: "= tarkasti" }),
        p("Tsemppiä!", "Good luck! Hang in there!", { note: "= Onnea!" }),
        p("tulla juttuun", "get on (with someone)", { note: "tulla (3), tulen juttuun = tulla toimeen" }),
        p("Voi hitsi!", "Oh shoot!"),
      ],
    },
  ],
  grammar: [
    {
      id: "c4-perfect",
      title: "Perfect",
      hints: [
        "Which person? Choose the form of olla first.",
        "Then the participle: -nut/-nyt for minä, sinä, hän; -neet for me, te, he. Type 3 doubles its consonant (-llut, -ssut); types 4 and 5 take -nnut.",
        "With an exact past time (eilen, viime viikolla) Finnish uses the simple past instead.",
      ],
      pages: [74, 75],
      blocks: [
        {
          type: "text",
          text: "The perfect is the present tense of olla plus the past participle: olen tehnyt, olemme tehneet. The negative uses the negative verb with ole: en ole tehnyt, emme ole tehneet. The participle ends in -nut/-nyt in the singular and in -neet in the plural.",
        },
        {
          type: "table",
          head: ["Type", "Basic form", "Participle", "Plural participle"],
          cols: ["base", "target", "target", "target"],
          rows: [
            ["1", "yrittää", "yrittänyt", "yrittäneet"],
            ["2", "jäädä", "jäänyt", "jääneet"],
            ["3", "seurustella", "seurustellut", "seurustelleet"],
            ["3", "ratkaista", "ratkaissut", "ratkaisseet"],
            ["4", "tarjota", "tarjonnut", "tarjonneet"],
            ["5", "ansaita", "ansainnut", "ansainneet"],
          ],
        },
        {
          type: "text",
          text: "Use the perfect for something that began in the past and still goes on, for something that happened when the exact time is not said, and for something that happened earlier and is noticed only now. In speech the participle often drops its last t: mä oon lukenu, me ollaan oltu.",
        },
        {
          type: "examples",
          items: [
            { target: "Olen asunut Suomessa kolme vuotta.", base: "I have lived in Finland for three years." },
            { target: "Liisa on valmistunut insinööriksi.", base: "Liisa has qualified as an engineer." },
            { target: "Yöllä on satanut lunta.", base: "It has snowed in the night." },
            { target: "Monet hakijat ovat soittaneet tänään.", base: "Many applicants have called today." },
            { target: "Kukaan ei ole vielä saanut paikkaa.", base: "Nobody has got the place yet." },
          ],
        },
      ],
      drills: [
        { id: "c4-perfect-01", prompt: "Olen ___ Suomessa kolme vuotta.", answer: "asunut", options: ["asunut", "asuneet", "asui"], hint: "asua", base: "I have lived in Finland for three years." },
        { id: "c4-perfect-02", prompt: "Liisa on ___ insinööriksi.", answer: "valmistunut", options: ["valmistunut", "valmistuneet", "valmistui"], hint: "valmistua", base: "Liisa has qualified as an engineer." },
        { id: "c4-perfect-03", prompt: "Yöllä on ___ lunta.", answer: "satanut", options: ["satanut", "sataneet", "satoi"], hint: "sataa", base: "It has snowed in the night." },
        { id: "c4-perfect-04", prompt: "Monet hakijat ovat ___ sinne.", answer: "soittaneet", options: ["soittaneet", "soittanut", "soittivat"], hint: "soittaa", base: "Many applicants have called there." },
        { id: "c4-perfect-05", prompt: "Kukaan ei ole vielä ___ paikkaa.", answer: "saanut", options: ["saanut", "saaneet", "sai"], hint: "saada", base: "Nobody has got the place yet." },
        { id: "c4-perfect-06", prompt: "He eivät ole ___ ketään.", answer: "valinneet", options: ["valinneet", "valinnut", "valitneet"], hint: "valita", base: "They haven't chosen anyone." },
        { id: "c4-perfect-07", prompt: "Oletko jo ___ ansioluettelon?", answer: "päivittänyt", options: ["päivittänyt", "päivittäneet", "päivitit"], hint: "päivittää", base: "Have you already updated the CV?" },
        { id: "c4-perfect-08", prompt: "Me olemme ___ rahaa lomaa varten.", answer: "säästäneet", options: ["säästäneet", "säästänyt", "säästimme"], hint: "säästää", base: "We have saved money for the holiday." },
        { id: "c4-perfect-09", prompt: "Hän on ___ harjoittelupaikkaan.", answer: "hakenut", options: ["hakenut", "hakeneet", "haki"], hint: "hakea", base: "She has applied for a work placement." },
        { id: "c4-perfect-10", prompt: "Oletteko ___ ongelman?", answer: "ratkaisseet", options: ["ratkaisseet", "ratkaissut", "ratkaisneet"], hint: "ratkaista", base: "Have you (all) solved the problem?" },
        { id: "c4-perfect-11", prompt: "En ole koskaan ___ salmiakkia.", answer: "maistanut", options: ["maistanut", "maistaneet", "maistoin"], hint: "maistaa", base: "I have never tasted salty liquorice." },
        { id: "c4-perfect-12", prompt: "He ovat ___ jo kaksi vuotta.", answer: "seurustelleet", options: ["seurustelleet", "seurustellut", "seurustelneet"], hint: "seurustella", base: "They have been together for two years already." },
        { id: "c4-perfect-13", prompt: "Työnantaja on ___ minulle paikkaa.", answer: "tarjonnut", options: ["tarjonnut", "tarjonneet", "tarjonut"], hint: "tarjota", base: "The employer has offered me a place." },
        { id: "c4-perfect-14", prompt: "Olen ___ soittaa sinne monta kertaa.", answer: "yrittänyt", options: ["yrittänyt", "yrittäneet", "yritin"], hint: "yrittää", base: "I have tried to call there many times." },
        { id: "c4-perfect-15", prompt: "Ette ole ___ minua.", answer: "ymmärtäneet", options: ["ymmärtäneet", "ymmärtänyt", "ymmärsitte"], hint: "ymmärtää", base: "You (all) haven't understood me." },
        { id: "c4-perfect-16", prompt: "Hän on ___ paljon rahaa.", answer: "ansainnut", options: ["ansainnut", "ansainneet", "ansaitnut"], hint: "ansaita", base: "She has earned a lot of money." },
        { id: "c4-perfect-17", prompt: "Hän on ___ kotiin.", answer: "jäänyt", options: ["jäänyt", "jääneet", "jäädnyt"], hint: "jäädä", base: "He has stayed at home." },
        { id: "c4-perfect-18", prompt: "Eilen ___ kaupassa.", answer: "kävin", options: ["kävin", "olen käynyt", "olin käynyt"], hint: "käydä", base: "Yesterday I went to the shop." },
      ],
    },
    {
      id: "c4-pluperfect",
      title: "Pluperfect",
      hints: [
        "Something happened before another past event: use the past tense of olla.",
        "olin, olit, oli + -nut/-nyt; olimme, olitte, olivat + -neet; negative: en ollut … emme olleet.",
      ],
      pages: [79],
      blocks: [
        {
          type: "text",
          text: "The pluperfect is the past tense of olla plus the past participle: olin tehnyt, olimme tehneet. The negative: en ollut tehnyt, emme olleet tehneet. Note that the negative uses the participle of olla too: ollut in the singular, olleet in the plural.",
        },
        {
          type: "table",
          head: ["Person", "Positive"],
          cols: ["target", "target"],
          rows: [
            ["minä", "olin hakenut"],
            ["sinä", "olit hakenut"],
            ["hän", "oli hakenut"],
            ["me", "olimme hakeneet"],
            ["te", "olitte hakeneet"],
            ["he", "olivat hakeneet"],
          ],
        },
        {
          type: "table",
          head: ["Person", "Negative"],
          cols: ["target", "target"],
          rows: [
            ["minä", "en ollut hakenut"],
            ["sinä", "et ollut hakenut"],
            ["hän", "ei ollut hakenut"],
            ["me", "emme olleet hakeneet"],
            ["te", "ette olleet hakeneet"],
            ["he", "eivät olleet hakeneet"],
          ],
        },
        {
          type: "text",
          text: "Use it for what had happened before something else in the past, when a story steps back in time, and when you report what someone told you about earlier events.",
        },
        {
          type: "examples",
          items: [
            { target: "Hänellä oli lyhyet hiukset, koska hän oli käynyt kampaajalla.", base: "She had short hair because she had been to the hairdresser's." },
            { target: "Menin keittiöön, kun olin herännyt.", base: "I went to the kitchen when I had woken up." },
            { target: "Hän kertoi, että hän oli saanut paikan.", base: "He said that he had got the place." },
            { target: "Kun soitin, paikka oli jo mennyt.", base: "When I called, the place had already gone." },
            { target: "Susan ei ollut jännittänyt ollenkaan.", base: "Susan hadn't been nervous at all." },
          ],
        },
      ],
      drills: [
        { id: "c4-pluperfect-01", prompt: "Hänellä oli lyhyet hiukset, koska hän ___ käynyt kampaajalla.", answer: "oli", options: ["oli", "on", "olivat"], base: "She had short hair because she had been to the hairdresser's." },
        { id: "c4-pluperfect-02", prompt: "Menin keittiöön, kun olin ___.", answer: "herännyt", options: ["herännyt", "heränneet", "heräsin"], hint: "herätä", base: "I went to the kitchen when I had woken up." },
        { id: "c4-pluperfect-03", prompt: "Lähdin ulos, kun olin ___ kahvia.", answer: "juonut", options: ["juonut", "juoneet", "join"], hint: "juoda", base: "I went out when I had drunk some coffee." },
        { id: "c4-pluperfect-04", prompt: "Hän kertoi, että hän oli ___ Maijan.", answer: "nähnyt", options: ["nähnyt", "nähneet", "näki"], hint: "nähdä", base: "She said that she had seen Maija." },
        { id: "c4-pluperfect-05", prompt: "Maija sanoi, että koirat ___ karanneet.", answer: "olivat", options: ["olivat", "oli", "ovat"], base: "Maija said that the dogs had run away." },
        { id: "c4-pluperfect-06", prompt: "Susan ei ___ jännittänyt ollenkaan.", answer: "ollut", options: ["ollut", "ole", "olleet"], base: "Susan hadn't been nervous at all." },
        { id: "c4-pluperfect-07", prompt: "Haastattelijat olivat ___ mukavia kysymyksiä.", answer: "kysyneet", options: ["kysyneet", "kysynyt", "kysyivät"], hint: "kysyä", base: "The interviewers had asked nice questions." },
        { id: "c4-pluperfect-08", prompt: "Kun tulimme kotiin, lapset olivat jo ___.", answer: "nukahtaneet", options: ["nukahtaneet", "nukahtanut", "nukahtivat"], hint: "nukahtaa", base: "When we came home, the children had already fallen asleep." },
        { id: "c4-pluperfect-09", prompt: "Heikki huomasi, että hän oli ___ väärän liitteen.", answer: "lähettänyt", options: ["lähettänyt", "lähettäneet", "lähetti"], hint: "lähettää", base: "Heikki noticed that he had sent the wrong attachment." },
        { id: "c4-pluperfect-10", prompt: "Me emme ___ käyneet Lapissa ennen sitä matkaa.", answer: "olleet", options: ["olleet", "ollut", "ole"], base: "We hadn't been to Lapland before that trip." },
        { id: "c4-pluperfect-11", prompt: "He ___ jo lähteneet, kun tulin.", answer: "olivat", options: ["olivat", "oli", "ovat"], base: "They had already left when I came." },
        { id: "c4-pluperfect-12", prompt: "Kun Heikki soitti, paikka oli jo ___.", answer: "mennyt", options: ["mennyt", "menneet", "meni"], hint: "mennä", base: "When Heikki called, the place had already gone." },
        { id: "c4-pluperfect-13", prompt: "Olimme ___ hakemuksen ennen lomaa.", answer: "lähettäneet", options: ["lähettäneet", "lähettänyt", "lähetimme"], hint: "lähettää", base: "We had sent the application before the holiday." },
        { id: "c4-pluperfect-14", prompt: "Et ___ tallentanut tiedostoa.", answer: "ollut", options: ["ollut", "olleet", "ole"], base: "You hadn't saved the file." },
      ],
    },
    {
      id: "c4-possessive",
      title: "Possessive suffixes",
      hints: [
        "Whose is it? Find the person.",
        "minun -ni, sinun -si, hänen -nsa/-nsä, meidän -mme, teidän -nne, heidän -nsa/-nsä; the stem keeps its strong grade.",
      ],
      pages: [92],
      blocks: [
        {
          type: "text",
          text: "In written Finnish a possessive suffix on the word shows whose it is: minun hakemukseni, sinun hakemuksesi. It is chosen by the person. In speech it is often left out: mun kirja, sun pöydän alla, teidän hakemukset.",
        },
        {
          type: "table",
          head: ["Person", "Example"],
          cols: ["base", "target"],
          rows: [
            ["minun", "hakemukseni"],
            ["sinun", "hakemuksesi"],
            ["hänen", "hakemuksensa"],
            ["meidän", "hakemuksemme"],
            ["teidän", "hakemuksenne"],
            ["heidän", "hakemuksensa"],
          ],
        },
        {
          type: "text",
          text: "Use it after the genitive of a personal pronoun (which may be left out: Ovatko tässä kaikki paperisi?), after oma, with toinen and itse, and in mielelläni, kanssani and pahoillani. Before the suffix the word keeps its strong grade, as in the mihin-form: pöytä → pöytäni, parveke → parvekkeeni, käsi → kätesi.",
        },
        {
          type: "examples",
          items: [
            { target: "Tämä on päivitetty ansioluetteloni.", base: "This is my updated CV." },
            { target: "Huomasitko ilmoituksemme lehdessä?", base: "Did you notice our advert in the paper?" },
            { target: "Voit lähettää hakemuksesi sähköpostilla.", base: "You can send your application by email." },
            { target: "Tulen mielelläni haastatteluun.", base: "I'll gladly come to the interview." },
            { target: "Hän esitteli itsensä minulle.", base: "He introduced himself to me." },
          ],
        },
      ],
      drills: [
        { id: "c4-possessive-01", prompt: "Tämä on minun ___.", answer: "ansioluetteloni", options: ["ansioluetteloni", "ansioluettelosi", "ansioluettelonsa"], hint: "ansioluettelo", base: "This is my CV." },
        { id: "c4-possessive-02", prompt: "Onko tämä sinun ___?", answer: "hakemuksesi", options: ["hakemuksesi", "hakemussi", "hakemuksenne"], hint: "hakemus", base: "Is this your application?" },
        { id: "c4-possessive-03", prompt: "Hänen ___ on myöhässä.", answer: "hakemuksensa", options: ["hakemuksensa", "hakemuksesi", "hakemuksemme"], hint: "hakemus", base: "His application is late." },
        { id: "c4-possessive-04", prompt: "Meidän ___ on lehdessä.", answer: "ilmoituksemme", options: ["ilmoituksemme", "ilmoitusmme", "ilmoituksenne"], hint: "ilmoitus", base: "Our advert is in the paper." },
        { id: "c4-possessive-05", prompt: "Teidän ___ on hyvä.", answer: "suunnitelmanne", options: ["suunnitelmanne", "suunnitelmamme", "suunnitelmasi"], hint: "suunnitelma", base: "Your (plural) plan is good." },
        { id: "c4-possessive-06", prompt: "Heidän ___ alkaa kuudelta.", answer: "työvuoronsa", options: ["työvuoronsa", "työvuoronne", "työvuoroni"], hint: "työvuoro", base: "Their shift starts at six." },
        { id: "c4-possessive-07", prompt: "Tulen ___ haastatteluun.", answer: "mielelläni", options: ["mielelläni", "mielellään", "mielellänne"], hint: "mielellään", base: "I'll gladly come to the interview." },
        { id: "c4-possessive-08", prompt: "Olemme ___, mutta paikka on jo mennyt.", answer: "pahoillamme", options: ["pahoillamme", "pahoillaan", "pahoillanne"], hint: "pahoillaan", base: "We're sorry, but the place has already gone." },
        { id: "c4-possessive-09", prompt: "Tulen keskustelemaan ___ tiistaina.", answer: "kanssasi", options: ["kanssasi", "kanssani", "kanssanne"], hint: "kanssa, sinä", base: "I'll come and talk with you on Tuesday." },
        { id: "c4-possessive-10", prompt: "Hän esitteli ___ minulle.", answer: "itsensä", options: ["itsensä", "itseni", "itsesi"], hint: "itse", base: "He introduced himself to me." },
        { id: "c4-possessive-11", prompt: "___ on taskussa.", answer: "Kätesi", options: ["Kätesi", "Käsisi", "Kädesi"], hint: "sinun käsi", base: "Your hand is in your pocket." },
        { id: "c4-possessive-12", prompt: "Tämä on ___.", answer: "pöytäni", options: ["pöytäni", "pöydäni", "pöytäsi"], hint: "minun pöytä", base: "This is my table." },
        { id: "c4-possessive-13", prompt: "Tämä on meidän ___.", answer: "parvekkeemme", options: ["parvekkeemme", "parvekemme", "parvekkeenne"], hint: "parveke", base: "This is our balcony." },
        { id: "c4-possessive-14", prompt: "Ovatko tässä kaikki ___?", answer: "paperisi", options: ["paperisi", "paperini", "paperinne"], hint: "sinun paperit", base: "Are all your papers here?" },
        { id: "c4-possessive-15", prompt: "He antoivat puhelinnumeronsa ___.", answer: "toisilleen", options: ["toisilleen", "toisillemme", "toisillenne"], hint: "toinen", base: "They gave each other their phone numbers.", alt: ["toisillensa"] },
        { id: "c4-possessive-16", prompt: "Kerroimme omista ___.", answer: "kokemuksistamme", options: ["kokemuksistamme", "kokemuksista", "kokemuksistanne"], hint: "kokemus", base: "We talked about our own experiences." },
      ],
    },
  ],
});
